export const proverbList = [
  {
    value: '가는 날이 장날이다',
    masking: '가는 날이',
  },
  {
    value: '가는 말이 고와야 오는 말이 곱다',
    masking: '가는 말이 고와야',
  },
  {
    value: '가랑잎이 솔잎더러 바스락거린다고 한다',
    masking: '가랑잎이 솔잎더러',
  },
  {
    value: '가재는 게 편이다',
    masking: '가재는'
  },
  {
    value: '가지 많은 나무에 바람 잘 날 없다',
    masking: '가지 많은 나무에',
  },
  {
    value: '갈수록 태산',
    masking: '갈수록'
  },
  {
    value: '같은 값이면 다홍치마',
    masking: '같은 값이면',
  },
  {
    value: '개같이 벌어서 정승같이 쓴다',
    masking: '개같이 벌어서',
  },
  {
    value: '개구리 올챙이 적 생각을 못 한다',
    masking: '개구리',
  },
  {
    value: '개똥도 약에 쓰려면 없다',
    masking: '개똥도',
  },
  {
    value: '개밥에 도토리',
    masking: '개밥에',
  },
  {
    value: '개버릇 남 못 준다',
    masking: '개버릇',
  },
  {
    value: '개천에서 용 난다',
    masking: '개천에서',
  },
  {
    value: '계란에도 뼈가 있다',
    masking: '계란에도',
  },
  {
    value: '고기는 씹어야 맛이요, 말은 해야 맛이라',
    masking: '고기는 씹어야 맛이요,',
  },
  {
    value: '고기도 먹어 본 사람이 잘 먹는다',
    masking: '고기도 잘 먹는다',
  },
  {
    value: '고래 싸움에 새우 등 터진다',
    masking: '고래 싸움에',
  },
  {
    value: '고양이 목에 방울 달기',
    masking: '고양이 목에',
  },
  {
    value: '공든 탑이 무너지랴',
    masking: '공든 탑이',
  },
  {
    value: '구더기 무서워 장 못 담글까',
    masking: '구더기 무서워',
  },
  {
    value: '구르는 돌은 이끼가 끼지 않는다',
    masking: '구르는 돌은',
  },
  {
    value: '구슬이 서 말이라도 꿰어야 보배라',
    masking: '구슬이 서 말이라도',
  },
  {
    value: '굴러 온 돌이 박힌 돌 뺀다',
    masking: '굴러 온 돌이',
  },
  {
    value: '귀에 걸면 귀걸이, 코에 걸면 코걸이',
    masking: '귀에 걸면 귀걸이,',
  },
  {
    value: '그림의 떡',
    masking: '그림의',
  },
  {
    value: '금강산도 식후경',
    masking: '금강산도',
  },
  {
    value: '까마귀 날자 배 떨어진다',
    masking: '까마귀 날자',
  },
  {
    value: '꿩 대신 닭',
    masking: '꿩 대신',
  },
  {
    value: '꿩 먹고 알 먹기',
    masking: '꿩 먹고',
  },
  {
    value: '남의 잔치에 감 놓아라 배 놓아라 한다',
    masking: '남의 잔치에',
  },
  {
    value: '낫 놓고 기역 자 모른다',
    masking: '낫 놓고',
  },
  {
    value: '낮말은 새가 듣고 밤말은 쥐가 듣는다',
    masking: '낮말은 새가 듣고',
  },
  {
    value: '내 코가 석자',
    masking: '내 코가',
  },
  {
    value: '누워서 침 뱉기',
    masking: '누워서',
  },
  {
    value: '누워서 떡먹기',
    masking: '누워서',
  },
  {
    value: '늦게 배운 도둑질에 날 새는 줄 모른다',
    masking: '늦게 배운 도둑질에',
  },
  {
    value: '다 된 밥에 재 뿌리기',
    masking: '다 된 밥에',
  },
  {
    value: '달면 삼키고 쓰면 뱉는다',
    masking: '달면 삼키고',
  },
  {
    value: '닭 잡아 먹고 오리발 내민다',
    masking: '닭 잡아 먹고',
  },
  {
    value: '도둑이 제 발 저리다',
    masking: '도둑이',
  },
  {
    value: '돌다리도 두들겨 보고 건너라',
    masking: '돌다리도',
  },
  {
    value: '되로 주고 말로 받는다',
    masking: '되로 주고',
  },
  {
    value: '등잔 밑이 어둡다',
    masking: '등잔 밑이',
  },
  {
    value: '땅 짚고 헤엄치기',
    masking: '땅 짚고',
  },
  {
    value: '똥 묻은 개가 겨 묻은 개 나무란다',
    masking: '똥 묻은 개가',
  },
  {
    value: '뛰는 놈 위에 나는 놈 있다',
    masking: '뛰는 놈 위에',
  },
  {
    value: '마른 하늘에 날벼락',
    masking: '마른 하늘에',
  },
  {
    value: '마파람에 게눈 감추듯 한다',
    masking: '마파람에',
  },
  {
    value: '말 한마디에 천 냥 빚도 갚는다',
    masking: '말 한마디에',
  },
  {
    value: '매도 먼저 맞는 놈이 낫다',
    masking: '매도 먼저',
  },
  {
    value: '모로 가도 서울만 가면 된다',
    masking: '모로 가도',
  },
  {
    value: '목구멍이 포도청',
    masking: '목구멍이',
  },
  {
    value: '못 먹는 감 찔러나 본다',
    masking: '못 먹는 감',
  },
  {
    value: '미운 놈 떡 하나 더 준다',
    masking: '미운 놈',
  },
  {
    value: '믿는 도끼에 발등 찍힌다',
    masking: '믿는 도끼에',
  },
  {
    value: '밑 빠진 독에 물 붓기',
    masking: '밑 빠진 독에',
  },
  {
    value: '바늘 가는 데 실 간다',
    masking: '바늘 가는 데',
  },
  {
    value: '바늘 도둑이 소 도둑 된다',
    masking: '바늘 도둑이',
  },
  {
    value: '배보다 배꼽이 더 크다',
    masking: '배보다 배꼽이',
  },
  {
    value: '밥 먹을 때는 개도 안 건든다',
    masking: '밥 먹을 때는',
  },
  {
    value: '백지장도 맞들면 낫다',
    masking: '백지장도',
  },
  {
    value: '뱁새가 황새 따라간다',
    masking: '뱁새가 황새',
  },
  {
    value: '벼룩의 간 빼먹기',
    masking: '벼룩의',
  },
  {
    value: '병 주고 약 준다',
    masking: '병 주고',
  },
  {
    value: '보기 좋은 떡이 먹기도 좋다',
    masking: '보기 좋은 떡이',
  },
  {
    value: '불난 집에 부채질 한다',
    masking: '불난 집에',
  },
  {
    value: '비 온 뒤에 땅이 굳어진다',
    masking: '비 온 뒤에',
  },
  {
    value: '빈 수레가 요란하다',
    masking: '빈 수레가',
  },
  {
    value: '빛 좋은 개살구',
    masking: '빛 좋은',
  },
  {
    value: '사공이 많으면 배가 산으로 올라간다',
    masking: '사공이 많으면',
  },
  {
    value: '사촌이 땅을 사면 배가 아프다',
    masking: '사촌이 땅을 사면',
  },
  {
    value: '새발의 피',
    masking: '새발의'
  },
  {
    value: '서당 개 삼 년에 풍월을 읊는다',
    masking: '서당 개 삼 년에',
  },
  {
    value: '세 살 버릇 여든까지 간다',
    masking: '세 살 버릇',
  },
  {
    value: '소문난 잔치에 먹을 것 없다',
    masking: '소문난 잔치에',
  },
  {
    value: '소 잃고 외양간 고친다',
    masking: '소 잃고',
  },
  {
    value: '쇠뿔도 단김에 빼랬다',
    masking: '쇠뿔도',
  },
  {
    value: '수박 겉 핥기',
    masking: '수박',
  },
  {
    value: '십 년이면 강산도 변한다',
    masking: '십 년이면',
  },
  {
    value: '아는 길도 물어 가라',
    masking: '아는 길도',
  },
  {
    value: '아니 땐 굴뚝에 연기 나랴',
    masking: '아니 땐 굴뚝에',
  },
  {
    value: '아닌 밤중에 홍두깨',
    masking: '아닌 밤중에',
  },
  {
    value: '약방에 감초',
    masking: '약방에',
  },
  {
    value: '어물전 망신은 꼴뚜기가 시킨다',
    masking: '어물전 망신은',
  },
  {
    value: '엎드려 절 받기',
    masking: '엎드려',
  },
  {
    value: '여자 셋이 모이면 접시가 깨진다',
    masking: '여자 셋이 모이면',
  },
  {
    value: '열 길 물 속은 알아도 한 길 사람 속은 모른다',
    masking: '열 길 물 속은 알아도',
  },
  {
    value: '열 번 찍어 안 넘어가는 나무 없다',
    masking: '열 번 찍어',
  },
  {
    value: '오뉴월 감기는 개도 안 걸린다',
    masking: '오뉴월 감기는',
  },
  {
    value: '오르지 못할 나무는 쳐다보지도 말아라',
    masking: '오르지 못할 나무는',
  },
  {
    value: '우물에 가서 숭늉 찾는다',
    masking: '우물에 가서'
  },
  {
    value: '울며 겨자 먹기',
    masking: '울며',
  },
  {
    value: '웃는 낯에 침 뱉으랴',
    masking: '웃는 낯에',
  },
  {
    value: '원수는 외나무 다리에서 만난다',
    masking: '원수는',
  },
  {
    value: '원숭이도 나무에서 떨어진다',
    masking: '원숭이도',
  },
  {
    value: '윗물이 맑아야 아랫물도 맑다',
    masking: '윗물이 맑아야',
  },
  {
    value: '자라 보고 놀란 가슴 솥뚜껑 보고 놀란다',
    masking: '자라 보고 놀란 가슴',
  },
  {
    value: '잘 자랄 나무는 떡잎부터 알아본다',
    masking: '잘 자랄 나무는',
  },
  {
    value: '작은 고추가 더 맵다',
    masking: '작은 고추가',
  },
  {
    value: '점잖은 고양이가 부뚜막에 먼저 올라간다',
    masking: '점잖은 고양이가',
  },
  {
    value: '종로에서 뺨 맞고 한강 가서 눈 흘긴다',
    masking: '종로에서 뺨 맞고',
  },
  {
    value: '좋은 약은 입에 쓰다',
    masking: '좋은 약은',
  },
  {
    value: '쥐구멍에도 볕 들 날이 있다',
    masking: '쥐구멍에도',
  },
  {
    value: '지렁이도 밟으면 꿈틀한다',
    masking: '지렁이도 밟으면'
  },
  {
    value: '천 리 길도 한 걸음부터',
    masking: '천 리 길도',
  },
  {
    value: '칼로 물 베기',
    masking: '칼로'
  },
  {
    value: '콩 심은 데 콩 나고 팥 심은 데 팥 난다',
    masking: '콩 심은 데 콩 나고',
  },
  {
    value: '티끌 모아 태산',
    masking: '티끌 모아',
  },
  {
    value: '하늘의 별 따기',
    masking: '하늘의'
  },
  {
    value: '하늘이 무너져도 솟아날 구멍은 있다',
    masking: '하늘이 무너져도',
  },
  {
    value: '하룻강아지 범 무서운 줄 모른다',
    masking: '하룻강아지',
  },
  {
    value: '한 귀로 듣고 한 귀로 흘린다',
    masking: '한 귀로 듣고'
  },
  {
    value: '한 술 밥에 배 부르랴',
    masking: '한 술 밥에',
  },
  {
    value: '호랑이 굴에 들어가야 호랑이 새끼를 잡는다',
    masking: '호랑이 굴에 들어가야',
  },
  {
    value: '호랑이에게 물려가도 정신만 바짝 차리면 산다',
    masking: '호랑이에게 물려가도',
  },
  {
    value: '호랑이도 제 말 하면 온다',
    masking: '호랑이도',
  },
]

export const idiomList = [
  { value: '가렴주구' },
  { value: '가인박명' },
  { value: '각골난망' },
  { value: '각자도생' },
  { value: '감언이설' },
  { value: '감탄고토' },
  { value: '개과천선' },
  { value: '거두절미' },
  { value: '건곤일척' },
  { value: '견물생심' },
  { value: '결자해지' },
  { value: '결초보은' },
  { value: '경거망동' },
  { value: '경국지색' },
  { value: '고진감래' },
  { value: '공명정대' },
  { value: '과유불급' },
  { value: '괄목상대' },
  { value: '군계일학' },
  { value: '권선징악' },
  { value: '근묵자흑' },
  { value: '금상첨화' },
  { value: '금의환향' },
  { value: '금지옥엽' },
  { value: '기고만장' },
  { value: '기사회생' },
  { value: '기상천외' },
  { value: '난형난제' },
  { value: '내우외환' },
  { value: '노심초사' },
  { value: '다다익선' },
  { value: '단도직입' },
  { value: '대기만성' },
  { value: '대동소이' },
  { value: '동문서답' },
  { value: '독불장군' },
  { value: '동병상련' },
  { value: '동상이몽' },
  { value: '두문불출' },
  { value: '등하불명' },
  { value: '마이동풍' },
  { value: '막상막하' },
  { value: '문전성시' },
  { value: '배은망덕' },
  { value: '백골난망' },
  { value: '백년해로' },
  { value: '백년서생' },
  { value: '백발백중' },
  { value: '백전노장' },
  { value: '백척간두' },
  { value: '부전자전' },
  { value: '부창부수' },
  { value: '분골쇠신' },
  { value: '불로소득' },
  { value: '사면초가' },
  { value: '사필귀정' },
  { value: '산전수전' },
  { value: '살신성인' },
  { value: '삼고초려' },
  { value: '상전벽해' },
  { value: '새옹지마' },
  { value: '선견지명' },
  { value: '설상가상' },
  { value: '소원성취' },
  { value: '속수무책' },
  { value: '송구영신' },
  { value: '수수방관' },
  { value: '순망치한' },
  { value: '신출귀몰' },
  { value: '아비귀환' },
  { value: '안빈낙도' },
  { value: '약육강식' },
  { value: '어부지리' },
  { value: '어불성설' },
  { value: '언중유골' },
  { value: '역지사지' },
  { value: '오리무중' },
  { value: '오비이락' },
  { value: '오합지졸' },
  { value: '와신상담' },
  { value: '외유내강' },
  { value: '용두사미' },
  { value: '우이독경' },
  { value: '우후죽순' },
  { value: '유구무언' },
  { value: '유명무실' },
  { value: '유유상종' },
  { value: '이심전심' },
  { value: '인사불성' },
  { value: '인산인해' },
  { value: '일거양득' },
  { value: '일망타진' },
  { value: '일사천리' },
  { value: '일석이조' },
  { value: '일장춘몽' },
  { value: '일취월장' },
  { value: '일편단심' },
  { value: '임기응변' },
  { value: '자가당착' },
  { value: '자수성가' },
  { value: '자업자득' },
  { value: '자초지종' },
  { value: '작심삼일' },
  { value: '적반하장' },
  { value: '전광석화' },
  { value: '전화위복' },
  { value: '조강지처' },
  { value: '조삼모사' },
  { value: '좌불안석' },
  { value: '죽마고우' },
  { value: '중구난방' },
  { value: '천고마비' },
  { value: '천재일우' },
  { value: '천진난만' },
  { value: '천하태평' },
  { value: '철두철미' },
  { value: '출가외인' },
  { value: '침소봉대' },
  { value: '타산지석' },
  { value: '파죽지세' },
  { value: '패가망신' },
  { value: '표리부동' },
  { value: '학수고대' },
  { value: '함흥차사' },
  { value: '호사다마' },
  { value: '호시탐탐' },
  { value: '화룡점정' },
  { value: '환골탈태' },
  { value: '회자정리' },
  { value: '횡설수설' },
]

export const fourLetterVocabList = [
  { value: '강강술래' },
  { value: '계란말이' },
  { value: '계좌번호' },
  { value: '고속도로' },
  { value: '고속버스' },
  { value: '고슴도치' },
  { value: '그린벨트' },
  { value: '네덜란드' },
  { value: '뉴발란스' },
  { value: '다이어트' },
  { value: '데리야끼' },
  { value: '동그랑땡' },
  { value: '된장찌개' },
  { value: '두루치기' },
  { value: '드래곤볼' },
  { value: '라이선스' },
  { value: '마요네즈' },
  { value: '뭉게구름' },
  { value: '밀폐용기' },
  { value: '바이올린' },
  { value: '브라우니' },
  { value: '브라우저' },
  { value: '블랙핑크' },
  { value: '비밀번호' },
  { value: '비트박스' },
  { value: '비트코인' },
  { value: '선글라스' },
  { value: '샌드박스' },
  { value: '샌드위치' },
  { value: '스마트폰' },
  { value: '스파게티' },
  { value: '스타벅스' },
  { value: '스타워즈' },
  { value: '스타필드' },
  { value: '아이언맨' },
  { value: '아프리카' },
  { value: '안전운전' },
  { value: '알레르기' },
  { value: '업데이트' },
  { value: '오토바이' },
  { value: '오토바이' },
  { value: '올리브영' },
  { value: '요구르트' },
  { value: '우루과이' },
  { value: '우리나라' },
  { value: '우리은행' },
  { value: '유통기한' },
  { value: '이구아나' },
  { value: '종이접기' },
  { value: '총각김치' },
  { value: '카놀라유' },
  { value: '카카오톡' },
  { value: '코스모스' },
  { value: '코스프레' },
  { value: '크레파스' },
  { value: '퀵서비스' },
  { value: '타임머신' },
  { value: '타임캡술' },
  { value: '파인애플' },
  { value: '포도씨유' },
  { value: '포스트잍' },
  { value: '프로그램' },
  { value: '프리미엄' },
  { value: '페브리즈' },
  { value: '프라이팬' },
  { value: '플라스크' },
  { value: '피라미드' },
  { value: '해바라기' },
  { value: '헬리콥터' },
  { value: '휴대전화' },
]

export const photoList = [
  { value: '윤아 소녀시대', url: '' },
  { value: '김태리', url: '' },
  { value: '남주혁', url: '' },
  { value: '이보영', url: '' },
  { value: '지성', url: '' },
  { value: '박지성 축구선수', url: '' },
  { value: '김태희', url: '' },
  { value: '한채영', url: '' },
  { value: '손흥민', url: '' },
  { value: '정우성', url: '' },
  { value: '이정재', url: '' },
  { value: '조이현', url: '' },
  { value: '이준기', url: '' },
  { value: '박지성', url: '' },
  { value: '이동국', url: '' },
  { value: '안정환', url: '' },
  { value: '이정현 가수', url: '' },
  { value: '김성주 아나운서', url: '' },
  { value: '김용만', url: '' },
  { value: '유재석', url: '' },
  { value: '지석진', url: '' },
  { value: '정준하', url: '' },
  { value: '박명수', url: '' },
  { value: '전소민', url: '' },
  { value: '하하', url: '' },
  { value: '이광수', url: '' },
  { value: '양세찬', url: '' },
  { value: '양세형', url: '' },
  { value: '김종국', url: '' },
  { value: '송지효', url: '' },
  { value: '강호동', url: '' },
  { value: '피오 블락비', url: '' },
  { value: '이수근', url: '' },
  { value: '은지원', url: '' },
  { value: '나영석', url: '' },
  { value: '송민호', url: '' },
  { value: '안재현', url: '' },
  { value: '김창완', url: '' },
  { value: '공유', url: '' },
  { value: '류진', url: '' },
  { value: '윤은혜', url: '' },
  { value: '아이유', url: '' },
  { value: '야옹이작가', url: '' },
  { value: '손예진', url: '' },
  { value: '장동민', url: '' },
  { value: '유세윤', url: '' },
  { value: '문세윤', url: '' },
  { value: '유상무', url: '' },
  { value: '이용진', url: '' },
  { value: '이진호', url: '' },
  { value: '뱃사공', url: '' },
  { value: '정호연', url: '' },
  { value: '김사랑', url: '' },
  { value: '백예린', url: '' },
  { value: '츄', url: '' },
  { value: '유리', url: '' },
  { value: '이효리', url: '' },
  { value: '성유리', url: '' },
  { value: '유진', url: '' },
  { value: '성시경', url: '' },
  { value: '장기하', url: '' },
  { value: '조세호', url: '' },
  { value: '장원영', url: '' },
  { value: '미주 러블리즈', url: '' },
  { value: '입짧은햇님', url: '' },
  { value: '김지원', url: '' },
  { value: '혜리', url: '' },
  { value: '박서준', url: '' },
  { value: '최우식', url: '' },
  { value: '김다미', url: '' },
  { value: '안재홍', url: '' },
  { value: '이병헌', url: '' },
  { value: '이민정', url: '' },
  { value: '현빈', url: '' },
  { value: '송혜교', url: '' },
  { value: '조승우', url: '' },
  { value: '조정석', url: '' },
  { value: '유연석', url: '' },
  { value: '전미도', url: '' },
  { value: '사나', url: '' },
  { value: '조나단', url: '' },
  { value: '조이', url: '' },
  { value: '박나래', url: '' },
  { value: '장도연', url: '' },
  { value: '베네딕트 컴버배치', url: '' },
  { value: '안젤리나 졸리', url: '' },
  { value: '임창정', url: '' },
  { value: '비욘세', url: '' },
  { value: '탐 크루즈', url: '' },
  { value: '이순재', url: '' },
  { value: '나문희', url: '' },
  { value: '윤여정', url: '' },
  { value: '박민영', url: '' },
  { value: '송강', url: '' },
  { value: '이성경', url: '' },
  { value: '구자철', url: '' },
  { value: '리오넬 메시', url: '' },
  { value: '윌 스미스', url: '' },
  { value: '모건 프리먼', url: '' },
  { value: '아만다 사이프리드', url: '' },
  { value: '한지민', url: '' },
  { value: '김혜자', url: '' },
  { value: '신구', url: '' },
  { value: '에릭', url: '' },
  { value: '정유미', url: '' },
  { value: '앤 헤서워이', url: '' },
  { value: '류승룡', url: '' },
  { value: '이하늬', url: '' },
  { value: '공명', url: '' },
  { value: '양조위', url: '' },
  { value: '천우희', url: '' },
  { value: '영심이', url: '' },
  { value: '빨간머리 앤', url: '' },
  { value: '달려라 하늬', url: '' },
  { value: '소닉', url: '' },
  { value: '피카츄', url: '' },
  { value: '배두나', url: '' },
  { value: '김혜수', url: '' },
  { value: '이제훈', url: '' },
  { value: '조진웅', url: '' },
  { value: '크러쉬', url: '' },
  { value: '송은이', url: '' },
  { value: '김숙', url: '' },
  { value: '지드래곤', url: '' },
  { value: '소연', url: '' },
  { value: '박재범', url: '' },
  { value: '태연', url: '' },
  { value: '임영웅', url: '' },
  { value: '승희', url: '' },
  { value: '보아', url: '' },
  { value: '카리나', url: '' },
  { value: '윈터', url: '' },
  { value: '빌리 아일리쉬', url: '' },
  { value: '제시', url: '' },
  { value: '지코', url: '' },
  { value: '전현무', url: '' },
  { value: '노주현', url: '' },
  { value: '박영규', url: '' },
  { value: '올라프', url: '' },
  { value: '보노보노', url: '' },
  { value: '짱구', url: '' },
  { value: '도라에몽', url: '' },
  { value: '뽀로로', url: '' },
  { value: '둘리', url: '' },
  { value: '또치', url: '' },
  { value: '고길동', url: '' },
  { value: '희동이', url: '' },
  { value: '신데렐라', url: '' },
  { value: '앨리스', url: '' },
  { value: '푸우', url: '' },
  { value: '심슨', url: '' },
  { value: '엘사 겨울왕국', url: '' },
  { value: '안나 겨울왕국', url: '' },
  { value: '뷔 bts', url: '' },
  { value: '이영자', url: '' },
  { value: '최화정', url: '' },
  { value: '최여진', url: '' },
  { value: '이현', url: '' },
  { value: '마시마로', url: '' },
  { value: '키티', url: '' },
  { value: '미키마우스', url: '' },
  { value: '주먹왕 랄프', url: '' },
  { value: '캐스퍼 아기유령', url: '' },
  { value: '휴잭맨', url: '' },
  { value: '탕웨이', url: '' },
  { value: '박찬욱', url: '' },
  { value: '봉준호', url: '' },
  { value: '송강호', url: '' },
  { value: '틸다 스윈튼', url: '' },
  { value: '박해일', url: '' },
  { value: '고아성', url: '' },
  { value: '오달수', url: '' },
  { value: '김명민', url: '' },
  { value: '신하균', url: '' },
  { value: '김희선', url: '' },
  { value: '차태현', url: '' },
  { value: '하정우', url: '' },
  { value: '주지훈', url: '' },
  { value: '마동석', url: '' },
  { value: '찬열', url: '' },
  { value: '카이', url: '' },
  { value: '백지영', url: '' },
  { value: '성동일', url: '' },
  { value: '정은지', url: '' },
  { value: '엠마왓슨', url: '' },
  { value: '최민식', url: '' },
  { value: '곽도원', url: '' },
  { value: '안성기', url: '' },
  { value: '고아라', url: '' },
  { value: '박소담', url: '' },
  { value: '이솜', url: '' },
  { value: '유노윤호', url: '' },
  { value: '규현', url: '' },
  { value: '태민', url: '' },
  { value: '신동', url: '' },
  { value: '화사', url: '' },
  { value: '한혜진', url: '' },
  { value: '강다니엘', url: '' },
  { value: '노홍철', url: '' },
  { value: '개리', url: '' },
  { value: '길', url: '' },
  { value: '황정민', url: '' },
  { value: '신봉선', url: '' },
  { value: '레오나르도 다빈치', url: '' },
  { value: '케이트 윈슬렛', url: '' },
  { value: '라이언 레이노즈', url: '' },
  { value: '조셉 고든 레빗', url: '' },
  { value: '레이첼 맥아담스', url: '' },
  { value: '이민호', url: '' },
  { value: '구혜선', url: '' },
  { value: '임시완', url: '' },
  { value: '강소라', url: '' },
  { value: '이성민', url: '' },
  { value: '마크 러펄로', url: '' },
  { value: '유아인', url: '' },
  { value: '김고은', url: '' },
  { value: '이동욱', url: '' },
  { value: '김세정', url: '' },
  { value: '한가인', url: '' },
  { value: '딘딘', url: '' },
  { value: '류준열', url: '' },
  { value: '김윤아', url: '' },
  { value: '라미란', url: '' },
  { value: '박보검', url: '' },
  { value: '고경표', url: '' },
  { value: '차승원', url: '' },
  { value: '손호준', url: '' },
  { value: '유해진', url: '' },
  { value: '배정남', url: '' },
  { value: '이선균', url: '' },
  { value: '고두심', url: '' },
  { value: '이지아', url: '' },
  { value: '장기용', url: '' },
  { value: '임수정', url: '' },
  { value: '소피 마르소', url: '' },
  { value: '오드리 햅번', url: '' },
  { value: '케이윌', url: '' },
  { value: '박효신', url: '' },
  { value: '문재인', url: '' },
  { value: '윤석열', url: '' },
  { value: '도널드 트럼프', url: '' },
  { value: '권정열', url: '' },
  { value: '김용명', url: '' },
  { value: '헤이즈', url: '' },
  { value: '비', url: '' },
  { value: '김태희', url: '' },
  { value: '김종민', url: '' },
  { value: '줄리아 로버츠', url: '' },
  { value: '휴 그랜트', url: '' },
  { value: '키이라 나이틀리', url: '' },
  { value: '차은우', url: '' },
  { value: '한소희', url: '' },
  { value: '구교환', url: '' },
  { value: '전지현', url: '' },
  { value: '고든램지', url: '' },
  { value: '박보영', url: '' },
  { value: '정해인', url: '' },
  { value: '안영미', url: '' },
  { value: '한효주', url: '' },
  { value: '박정민', url: '' },
  { value: '공효진', url: '' },
  { value: '강하늘', url: '' },
  { value: '김지석', url: '' },
  { value: '이다희', url: '' },
  { value: '김영철', url: '' },
  { value: '민경훈', url: '' },
  { value: '서장훈', url: '' },
  { value: '이상민', url: '' },
  { value: '오은영', url: '' },
  { value: '이승기', url: '' },
  { value: '김무열', url: '' },
  { value: '윤승아', url: '' },
  { value: '정경호', url: '' },
  { value: '박미선', url: '' },
  { value: '이정은', url: '' },
  { value: '이시영', url: '' },
  { value: '강혜정', url: '' },
  { value: '타블로', url: '' },
  { value: 'KCM', url: '' },
  { value: '원슈타인', url: '' },
  { value: '노제', url: '' },
  { value: '가비', url: '' },
  { value: '셀레나 고메즈', url: '' },
  { value: '저스틴 비버', url: '' },
  { value: '아리아나 그란데', url: '' },
  { value: '이찬혁', url: '' },
  { value: '이수현', url: '' },
  { value: '홍현희', url: '' },
  { value: '제이슨', url: '' },
  { value: '김남길', url: '' },
  { value: '엄정화', url: '' },
  { value: '정형돈', url: '' },
  { value: '정형돈', url: '' },
  { value: '로꼬', url: '' },
  { value: '코드쿤스트', url: '' },
  { value: '미노이', url: '' },
  { value: '장윤정', url: '' },
  { value: '김남길', url: '' },
  { value: '장윤주', url: '' },
  { value: '한해', url: '' },
  { value: '넉살', url: '' },
  { value: '이종혁', url: '' },
  { value: '송일국', url: '' },
  { value: '박대기기자', url: '' },
  { value: '양준혁', url: '' },
  { value: '현주엽', url: '' },
  { value: '이덕화', url: '' },
  { value: '이형택', url: '' },
  { value: '박세리', url: '' },
  { value: '모태범', url: '' },
  { value: '김연아', url: '' },
  { value: '박태환', url: '' },
  { value: '김요한', url: '' },
  { value: '김동현', url: '' },
  { value: '김은정', url: '' },
  { value: '유시민', url: '' },
  { value: '유희열', url: '' },
  { value: '이적', url: '' },
  { value: '주현영', url: '' },
  { value: '김민교', url: '' },
  { value: '정상훈', url: '' },
  { value: '강유미', url: '' },
  { value: '죠지', url: '' },
  { value: '변요한', url: '' },
  { value: '설경구', url: '' },
  { value: '양동근', url: '' },
  { value: '조인성', url: '' },
  { value: '이영애', url: '' },
  { value: '하비에르 바르뎀', url: '' },
  { value: '히스 레저', url: '' },
  { value: '권오중', url: '' },
  { value: '김래원', url: '' },
  { value: '진구', url: '' },
  { value: '탁재훈', url: '' },
  { value: '김수미', url: '' },
  { value: '이호철', url: '' },
  { value: '이경영', url: '' },
  { value: '류승범', url: '' },
  { value: '염정아', url: '' },
  { value: '윤세아', url: '' },
  { value: '김우빈', url: '' },
  { value: '이수혁', url: '' },
  { value: '서인국', url: '' },
  { value: '최지우', url: '' },
  { value: '권상우', url: '' },
  { value: '장근석', url: '' },
  { value: '유승호', url: '' },
  { value: '유이', url: '' },
  { value: '박신혜', url: '' },
  { value: '이종석', url: '' },
  { value: '김영광', url: '' },
  { value: '전도연', url: '' },
  { value: '김주혁', url: '' },
  { value: '진서연', url: '' },
  { value: '한석규', url: '' },
  { value: '박신양', url: '' },
  { value: '김정은', url: '' },
  { value: '김정은', url: '' },
  { value: '박근혜', url: '' },
  { value: '이명박', url: '' },
  { value: '버락 오바마', url: '' },
  { value: '조지 부시', url: '' },
  { value: '푸틴', url: '' },
  { value: '마윈', url: '' },
  { value: '워렌버핏', url: '' },
  { value: '존리', url: '' },
  { value: '빌게이츠', url: '' },
  { value: '스티브잡스', url: '' },
  { value: '세종대왕', url: '' },
  { value: '이순신장군', url: '' },
  { value: '김영철', url: '' },
  { value: '유관순', url: '' },
  { value: '김구', url: '' },
  { value: '윤봉길', url: '' },
  { value: '안중근', url: '' },
  { value: '아인슈타인', url: '' },
  { value: '베토벤', url: '' },
  { value: '바흐', url: '' },
  { value: '빈센트 반 고흐', url: '' },
  { value: '모나리자', url: '' },
  { value: '에단 호크', url: '' },
  { value: '쿠사마 야요이', url: '' },
  { value: '엔디워홀', url: '' },
  { value: '살바도르 다리', url: '' },
  { value: '프리다칼로', url: '' },
  { value: '간디', url: '' },
  { value: '마틴 루터 킹', url: '' },
  { value: '체 게바라', url: '' },
  { value: '레오나르도 디카프리오', url: '' },
  { value: '클레오 파트라', url: '' },
  { value: '마돈나', url: '' },
  { value: '마이클잭슨', url: '' },
  { value: '프레디 머큐리', url: '' },
  { value: '마릴린먼로', url: '' },
  { value: '신사임당', url: '' },
  { value: '정주영', url: '' },
  { value: '민경훈', url: '' },
  { value: '김희철', url: '' },
  { value: '오드리햅번', url: '' },
  { value: '나훈이', url: '' },
  { value: '태진아', url: '' },
  { value: '설운도', url: '' },
  { value: '김구라', url: '' },
  { value: '윤종신', url: '' },
  { value: '김국진', url: '' },
  { value: '주호민', url: '' },
  { value: '이말년', url: '' },
  { value: '법정스님', url: '' },
  { value: '김수환추기경', url: '' },
  { value: '이건희', url: '' },
  { value: '이재용', url: '' },
  { value: '홍석천', url: '' },
  { value: '김민경', url: '' },
  { value: '준호', url: '' },
  { value: '제니', url: '' },
  { value: '한선화', url: '' },
  { value: '박인환', url: '' },
  { value: '장사익', url: '' },
  { value: '김덕수', url: '' },
  { value: '엄홍길', url: '' },
  { value: '가인', url: '' },
  { value: '별', url: '' },
  { value: '선우용녀', url: '' },
  { value: '김부자', url: '' },
  { value: '양희은', url: '' },
  { value: '천호진', url: '' },
  { value: '김혜숙', url: '' },
  { value: '김갑수 배우', url: '' },
  { value: '서현진', url: '' },
  { value: '이서진', url: '' },
  { value: '마이클조던', url: '' },
  { value: '르브론제임스', url: '' },
  { value: '타이거우즈', url: '' },
  { value: '옹박', url: '' },
  { value: '주성치', url: '' },
  { value: '김수현', url: '' },
  { value: '박지선교수님', url: '' },
  { value: '이수정교수님', url: '' },
  { value: '권일용 프로파일러', url: '' },
  { value: '표창원 프로파일러', url: '' },
  { value: '이수정교수님', url: '' },
  { value: '김태호', url: '' },
  { value: '씨엘', url: '' },
  { value: '크리스탈', url: '' },
  { value: '김두영', url: '' },
  { value: '신세경', url: '' },
  { value: '리정', url: '' },
  { value: '혁오', url: '' },
  { value: '한효주', url: '' },
  { value: '이진욱', url: '' },
  { value: '이경규', url: '' },
  { value: '최불암', url: '' },
  { value: '조니뎁', url: '' },
  { value: '김유정', url: '' },
  { value: '기네스 팰트로', url: '' },
  { value: '두아리파', url: '' },
  { value: '선미', url: '' },
  { value: '현아', url: '' },
  { value: '최시원', url: '' },
  { value: '호날두', url: '' },
  { value: '베컴', url: '' },
]

export const animalList = [
  { value: '고양이' },
  { value: '개(강아지)' },
  { value: '개미' },
  { value: '게' },
  { value: '개구리' },
  { value: '고슴도치' },
  { value: '거북이' },
  { value: '고래' },
  { value: '기린' },
  { value: '나비' },
  { value: '나무늘보' },
  { value: '너구리' },
  { value: '늑대' },
  { value: '다람쥐' },
  { value: '닭' },
  { value: '도마뱀' },
  { value: '돼지' },
  { value: '말' },
  { value: '박쥐' },
  { value: '비둘기' },
  { value: '모기' },
  { value: '미어켓' },
  { value: '바퀴벌레' },
  { value: '병아리' },
  { value: '사자' },
  { value: '상어' },
  { value: '소' },
  { value: '새우' },
  { value: '수달' },
  { value: '스컹크' },
  { value: '악어' },
  { value: '앵무새' },
  { value: '양' },
  { value: '여우' },
  { value: '오리' },
  { value: '조개' },
  { value: '캥거루' },
  { value: '타조' },
  { value: '토끼' },
  { value: '파리' },
  { value: '팬더' },
  { value: '하이에나' },
  { value: '햄스터' },
  { value: '호랑이' },
]

export const movieList = [
  {
    value: '쇼생크 탈출',
    screenshot: 'https://search.pstatic.net/common?quality=75&direct=true&src=https%3A%2F%2Fmovie-phinf.pstatic.net%2F20160216_244%2F1455603307357dh5WY_JPEG%2Fmovie_image.jpg'
  },
  {
    value: '라라랜드',
    screenshot: 'https://search.pstatic.net/common?quality=75&direct=true&src=https%3A%2F%2Fmovie-phinf.pstatic.net%2F20161101_284%2F14779623657454Yd9v_JPEG%2Fmovie_image.jpg'
  },
  {
    value: '인턴',
    screenshot: 'https://search.pstatic.net/common?quality=75&direct=true&src=https%3A%2F%2Fmovie-phinf.pstatic.net%2F20150916_225%2F1442389492471m9uGb_JPEG%2Fmovie_image.jpg'
  },
  {
    value: '내부자들', scriptList: [
      {
        screenshot: 'images/movie/soqnwkemf.png',
        script: '모히또 가서 몰디브 한 잔할라니까',
      }
    ]
  },
  {
    value: '부당거래', scriptList: [
      {
        screenshot: 'images/movie/qnekdrjfo.png',
        script: '호의가 계속되면 그게 권리인줄 알아요',
      }
    ]
  },
  {
    value: '범죄와의 전쟁', scriptList: [
      {
        screenshot: 'images/movie/qjawhldhkdmlwjswod.png',
        script: '느그 서장 남천동 살제?',
      },
      {
        screenshot: 'images/movie/sksflsksfl.png',
        script: '난리났네 난리났어 어디 오빠 없는 사람 서러워 살겠나',
      }
    ]
  },
  {
    value: '추격자', scriptList: [
      {
        screenshot: 'images/movie/cnrurwk.png',
        script: '야 4885 너지?',
      }
    ]
  },
  {
    value: '늑대의 유혹',
    screenshot: 'https://search.pstatic.net/common?quality=75&direct=true&src=https%3A%2F%2Fmovie-phinf.pstatic.net%2F20160204_147%2F1454589383205v7NjP_JPEG%2Fmovie_image.jpg',
  },
  {
    value: '노인을 위한 나라는 없다',
    screenshot: 'https://search.pstatic.net/common?quality=75&direct=true&src=https%3A%2F%2Fmovie-phinf.pstatic.net%2F20180813_232%2F1534121461320IfxaF_JPEG%2Fmovie_image.jpg',
  },
  { value: '말할 수 없는 비밀', screenshot: 'images/movie/akfgkftndjqtsmsqlalf.png', },
  {
    value: '어벤져스: 엔드게임',
    screenshot: 'https://img.huffingtonpost.com/asset/5cc67e6d24000033007782ea.png?ops=scalefit_630_noupscale',
  },
  {
    value: '미스터 & 미세스 스미스',
    screenshot: 'https://search.pstatic.net/common?quality=75&direct=true&src=https%3A%2F%2Fmovie-phinf.pstatic.net%2F20111223_205%2F1324582189493CRHBz_JPEG%2Fmovie_image.jpg',
  },
  {
    value: '신세계', scriptList: [
      {
        screenshot: 'images/movie/tlstprp.png',
        script: '뭐 갈때 가더라도 담배 한대 정도는 괜찮잖아?',
      },
      {
        screenshot: 'images/movie/rjwnrrl.png',
        script: '거 죽기 딱 좋은 날씨네',
      },
      {
        screenshot: 'images/movie/ttlstprp.png',
        script: '중구 형님 거 장난이 너무 심한거 아니오',
      },
      {
        screenshot: 'https://blog.kakaocdn.net/dn/wzppq/btqTvRDBMok/gzeVAiVl7syECpaYfKW5H1/img.jpg',
        script: '살려는 드릴께',
      },
      {
        screenshot: 'images/movie/emfndhkemfndhk.png',
        script: '드루와 드루와',
      },
      {
        screenshot: 'images/movie/tlstprpvmfhwprxm.png',
        script: '신세계 신세계 프로젝트',
      }
    ]
  },
  {
    value: '건축학개론', scriptList: [
      {
        screenshot: 'images/movie/rjscnrgkrrofhs.png',
        script: '키스라는건 말이야 봐봐 입술이 딱 붙잖아 근데 걔혀 니혀가 자연스럽게 들어온다고 스르륵 뱀처럼...',
      }
    ]
  },
  {
    value: '내 머리 속의 지우개', scriptList: [
      {
        screenshot: 'https://img.sbs.co.kr/newimg/news/20181211/201259490.jpg',
        script: '이거 마시면 나랑 사귀는거다?',
      }
    ]

  },
  {
    value: '1987', scriptList: [
      {
        screenshot: 'https://w.namu.la/s/760efbabc2b8a054e96b9b076662dadd3b27e17d8edfe33b20a215b834d7b440aba6bf8fda4d5a418ffcfc615387ef2030af9ad3b184beb35c681c23344030e0c16165830c53fc9969c4101513d76580fd9b0c5bec43328b26dffddf7265daf4',
        script: '그거 손으로 닦음 더 따가워요, 세수하세요.',
      }
    ]
  },
  {
    value: '캐치 미 이프 유캔',
    screenshot: 'https://movie-phinf.pstatic.net/20111223_19/1324578807821Gmlct_JPEG/movie_image.jpg',
  },
  { value: '시동', screenshot: 'images/movie/tlehd.png' },
  {
    value: '가타카',
    screenshot: 'https://movie-phinf.pstatic.net/20111222_47/1324541845985qvCC9_JPEG/movie_image.jpg',
  },
  {
    value: '비포선라이즈',
    screenshot: 'https://movie-phinf.pstatic.net/20160324_259/1458798387486UACDQ_JPEG/movie_image.jpg',
  },
  {
    value: '극한직업',
    scriptList: [
      {
        screenshot: 'images/movie/d0050518_5c87c9cad0963.png',
        script: '지금까지 이런 맛은 없었다. 이것은 갈비인가 통닭인가',
      }
    ]
  },
  {
    value: '어바웃타임',
    screenshot: 'https://movie-phinf.pstatic.net/20131017_111/13819797321865byFb_JPEG/movie_image.jpg',
  },
  {
    value: '트루먼쇼',
    screenshot: 'https://movie-phinf.pstatic.net/20111221_261/1324475725070XHLGR_JPEG/movie_image.jpg',
  },
  {
    value: '화양연화',
    screenshot: 'https://movie-phinf.pstatic.net/20201203_112/1606986402195J3Gbd_JPEG/movie_image.jpg',
  },
  {
    value: '소림축구',
    screenshot: 'https://movie-phinf.pstatic.net/20111222_80/1324544020449IrzCV_JPEG/movie_image.jpg',
  },
  {
    value: '노팅힐',
    screenshot: 'https://movie-phinf.pstatic.net/20190402_153/1554169860877NDhCI_JPEG/movie_image.jpg',
  },
  {
    value: '이웃집 토토로',
    screenshot: 'https://movie-phinf.pstatic.net/20190605_90/1559698578705XYqxw_JPEG/movie_image.jpg',
  },
  {
    value: '하울의 움직이는 성',
    screenshot: 'https://movie-phinf.pstatic.net/20141119_47/1416357055571DHsVB_JPEG/movie_image.jpg',
  },
  {
    value: '센과 치히로의 행방불명',
    screenshot: 'https://movie-phinf.pstatic.net/20150108_83/1420706407615GKsAa_JPEG/movie_image.jpg',
  },
  {
    value: '인터스텔라',
    screenshot: 'https://movie-phinf.pstatic.net/20141112_202/1415776906972fTbqE_JPEG/movie_image.jpg',
  },
  {
    value: '기생충',
    scriptList: [
      {
        screenshot: 'https://i.ytimg.com/vi/j_SiPdl-9c8/sddefault.jpg',
        script: '아들아 너는 다 계획이 있구나',
      },
      {
        screenshot: 'images/movie/jessica.png',
        script: '제시카 외동딸 일리노이 시카고 과선배는 김진모 그는 네 사촌.'
      },
      {
        screenshot: 'images/movie/tkdwldwjr.png',
        script: '진짜 상징적이다.',
      },
      {
        screenshot: 'images/movie/dhk.png',
        script: '와 여기 진짜 상징적이다. 아부지 우리가 기사식당에서 밥을 먹고있네요 하필이면',
      },
      {
        screenshot: 'images/movie/tlfwjsdmsrltp.png',
        script: '실전은 기세야. 기세. 알겠어?'
      },
      {
        screenshot: 'images/movie/belt.png',
        script: 'I\'m deadly serious. 믿는 사람 소개로 연결 연결.. 이게 베스트 인거 같아요. 일종의 뭐랄까 믿음의 벨트?'
      },
      {
        screenshot: 'images/movie/sofurkqhtlrp.png',
        script: '같이 내려가 보시겠어요?',
      },
      {
        screenshot: 'images/movie/respect.png',
        script: 'Respect!!!',
      },
      {
        screenshot: 'images/movie/noplan.png',
        script: '너 절대 실패하지 않는 계획이 뭔줄 아니? 무계획이야, 무계획. No plan.',
      },
    ]
  },
  {
    value: '완벽한 타인',
    screenshot: 'https://movie-phinf.pstatic.net/20181001_259/1538357997818FRHvN_JPEG/movie_image.jpg',
  },
  {
    value: '당신 거기 있어줄래요',
    screenshot: 'https://movie-phinf.pstatic.net/20161031_217/1477891709300J1mdG_JPEG/movie_image.jpg',
  },
  {
    value: '택시운전사',
    screenshot: 'https://movie-phinf.pstatic.net/20170619_291/1497860513033DKbVq_JPEG/movie_image.jpg',
  },
  {
    value: '아바타',
    scriptList: [
      {
        screenshot: 'https://t1.daumcdn.net/cfile/tistory/192262044B94BE3B72',
        script: 'I see you',
      }
    ]
  },
  {
    value: '아가씨',
    screenshot: 'https://movie-phinf.pstatic.net/20160411_25/1460361115500WvGpr_JPEG/movie_image.jpg',
  },
  {
    value: '엽기적인 그녀',
    scriptList: [
      {
        screenshot: 'https://mblogthumb-phinf.pstatic.net/MjAxOTA1MzBfNzEg/MDAxNTU5MjIzNzE1MTAw.eykWNwSGz2unTj-vfrkq0Mt-WoveJBFVd-Edqe9d78Yg.Djez5bHlLWekwF7ys7yTm0fvP6whdY9f4Oy9FqFUQoMg.PNG.kimdg4488/SE-6fbb9ac2-6bec-4645-a53b-e24f65bcc506.png',
        script: '견우야 미안해 나도 어쩔 수 없는 여자인가봐',
      }
    ]
  },
  {
    value: '신과함께 죄와 벌',
    screenshot: 'https://movie-phinf.pstatic.net/20171211_26/1512956431379ySenO_JPEG/movie_image.jpg',
  },
  {
    value: '리틀포레스트',
    screenshot: 'https://movie-phinf.pstatic.net/20180205_174/1517796368738tiA8V_JPEG/movie_image.jpg',
  },
  {
    value: '타짜',
    scriptList: [
      {
        screenshot: 'https://pds.joongang.co.kr/news/component/htmlphoto_mmdata/202001/30/6034a444-c3cb-4d41-af98-08aa8947cb80.jpg',
        script: '묻고 더블로 가'
      },
      {
        screenshot: 'https://image.kmib.co.kr/online_image/2019/0923/611718110013743046_1.jpg',
        script: '마포 대교는 무너졌냐 이 새끼야',
      },
      {
        screenshot: 'images/movie/dleoskdhsduwk.png',
        script: '나 이대나온 여자야',
      },
      {
        screenshot: 'images/movie/thftndlTdj.png',
        script: '쏠 수 있어',
      },
      {
        screenshot: 'images/movie/ehdwkrrmaks.png',
        script: '동작그만 밑장빼기냐?',
      },
      {
        screenshot: 'images/movie/rktmadpqltnrk.png',
        script: '싸늘하다, 가슴에 비수가 날아와 꽃힌다. 하지만 걱정하지마라. 손은 눈보다 빠르니까.',
      }
    ],
  },
  {
    value: '친구',
    scriptList: [
      { screenshot: 'images/movie/smrmdkqnwl.png', script: '느그 아부지 뭐하시노?' },
      { screenshot: 'images/movie/slrkrkfk.png', script: '니가 가라 하와이' },
      { screenshot: 'images/movie/tlekqkfl.png', script: '내가 니 시다바리가' },
      { screenshot: 'images/movie/rhakgofk.png', script: '마 마이 무따 아이가 고마해라' }
    ]
  },
  { value: '바람', scriptList: [
      { screenshot: 'images/movie/rmfkansdkseho.png', script: '그라믄 안돼 정상한테 처 밟히고 그렇게 해서는 안돼!' }
    ]
  },
  { value: '홀리데이', scriptList: [
      { screenshot: 'images/movie/ghfflepdl.png', script: '이건 경고 사격을 위한 공포탄', },
      { screenshot: 'images/movie/anwjsdbwhl.png', script: '유전무죄 무전유죄', }
    ]
  },
  { value: '실미도', scriptList: [
      { screenshot: 'images/movie/silmido01.png', script: '비겁한 변명입니다!' },
      { screenshot: 'images/movie/silmido02.png', script: '날 쏘고가라' },
    ]
  },
  { value: '친절한 금자씨', scriptList: [
      { screenshot: 'images/movie/geumja.png', script: '너나 잘하세요' }
    ]
  },
  { value: '봄날은 간다', scriptList: [
      { screenshot: 'images/movie/bomnal01.png', script: '라면 먹을래요?' },
      { screenshot: 'images/movie/bomnal02.png', script: '어떻게 사랑이 변하니?' }
    ]
  },
  { value: '올드보이', scriptList: [
      { screenshot: 'images/movie/oldboy01.png', script: '누구냐 너' },
      { screenshot: 'images/movie/oldboy02.png', script: '잘가라 오대수' },
      { screenshot: 'images/movie/oldboy03.png', script: '내가 이제부터 이우진의 개야. 나 개새끼야. 왈 왈왈 왈왈. 꼬리 살랑살랑' },
      { screenshot: 'images/movie/oldboy04.png', script: '사랑해요 아저씨' },
    ]
  },
  { value: '명량', scriptList: [
      { screenshot: 'images/movie/myeongryang02.png', script: '아직 신에게는 아직 12척의 배가 남아있사옵니다.' },
      { screenshot: 'images/movie/myeongryang01.png', script: '목숨에 기대지마라. 살고자하면 필히 죽을것이고 또한 죽고자하면 살것이니 ' }
    ]
  },
  { value: '해바라기', scriptList: [
      { screenshot: 'images/movie/sunflower01.png', script: '나다 이씹새끼야' },
      { screenshot: 'images/movie/sunflower02.png', script: '꼭 그렇게 다 가져 가야만 속이후련했냐!!' }
    ] },
  { value: '관상', scriptList: [
      { screenshot: 'images/movie/face01.png', script: '어째 내 얼굴이 왕이될 상인가' },
      { screenshot: 'images/movie/face02.png', script: '헌데 관상가 양반, 생각해 보니 영 이상하구만. 이미 나는 왕이 되었는데 왕이 될 상이라니.' }
    ] },
  {
    value: '도둑들',
    scriptList: [
      { screenshot: 'images/movie/thieves01.png', script: '안가니? (저 아세요?) 내가 널 어떻게 아니? 내 차 끌고 왔으니까 알지.'},
      { screenshot: 'images/movie/thieves02.png', script: '내가 볼 땐 어마어마한 썅년같애'},
    ]
  },
  {
    value: '베테랑',
    scriptList: [
      { screenshot: 'images/movie/veteran01.png', script: '어이가 없네 ?' },
      { screenshot: 'images/movie/veteran02.png', script: '우리 쪽팔리게 살진 말자' },
      { screenshot: 'images/movie/veteran03.png', script: '야 우리가 돈이 없지 가오가 없어?' },
      { screenshot: 'images/movie/veteran04.png', script: '나 여기 아트박스 사장인데...' }
    ],
  },
  { value: '말아톤', scriptList: [
      { screenshot: 'images/movie/marathon.png', script: '초원이 다리는 백만불짜리 다리' }
    ] },
  { value: '박하사탕', scriptList: [
      { screenshot: 'images/movie/mint.png', script: '나 다시 돌아갈래~~~~~' }
    ] },
  { value: '왕의 남자', scriptList: [
      { screenshot: 'images/movie/dhkddmlskawk.png', script: '너 거기있고 나여기있지? 아니지 너 여기있고 나거기있지?' }
    ] },
  { value: '달콤한 인생', scriptList: [
      { screenshot: 'images/movie/sweetlife.png', script: '넌 나에게 모욕감을 줬어' }
    ] },
  { value: '곡성', scriptList: [
      { screenshot: 'images/movie/goksung01.png', script: '뭣이 중헌디?' },
      { screenshot: 'images/movie/goksung02.png', script: '그 놈은 미끼를 던져분 것이고, 자네 딸래미는 고것을 콱 물어분 것이여' },
      { screenshot: 'images/movie/goksung03.png', script: '와따시다!!!!' }
    ] },
  { value: '엑시트', scriptList: [
      { screenshot: 'images/movie/exit.png', script: '따따따 따 따 따 따따따' }
    ] },
  { value: '알라딘', screenshot: 'https://search.pstatic.net/common?quality=75&direct=true&src=https%3A%2F%2Fmovie-phinf.pstatic.net%2F20190417_212%2F1555463319238lklmS_JPEG%2Fmovie_image.jpg' },
  { value: '라이온킹', screenshot: 'http://t1.daumcdn.net/cfile/116955364EC098F61B' },
  { value: '신데렐라', screenshot: 'images/movie/cinderella.png' },
  { value: '살인의 추억', scriptList:[
      { screenshot: 'images/movie/tkfdlsdmlcndjr01.png', script: '향숙이? 향숙이 예쁘지' },
      { screenshot: 'images/movie/tkfdlsdmlcndjr02.png', script: '밥은 먹고 다니냐?' }
    ] },
  { value: '500일의 썸머', screenshot: 'http://t1.daumcdn.net/movie/360f48053a5d34a8bb3b7cbe1a2df633d5ca0770' },
  { value: '쿵푸팬더', screenshot: 'http://t1.daumcdn.net/cfile/13497810B04369D307' },
  { value: '설국열차', screenshot: 'http://t1.daumcdn.net/cfile/2740BA4751D65C7F33' },
  { value: '오아시스', screenshot: 'images/movie/oasis.png' },
  { value: '라푼젤', screenshot: 'http://t1.daumcdn.net/cfile/14378B364D51091514' },
  { value: '공조', screenshot: 'http://t1.daumcdn.net/movie/962fc7b195455f21a4a7da7617283291f43d05fa' },
  { value: '검사외전', screenshot: 'http://t1.daumcdn.net/movie/fc9b3cef912a7c5546104fc4f4db8ba54df362d8' },
  { value: '좋은놈 나쁜놈 이상한놈', screenshot: 'http://t1.daumcdn.net/cfile/15492110B04F886224' },
  { value: '국가대표', screenshot: 'http://t1.daumcdn.net/cfile/1349CB254A38FD92C3' },
  { value: '아수라', screenshot: 'http://t1.daumcdn.net/movie/e6e4e6cafa20e1e0cc6dfb26723b18d0f34ff753' },
  { value: '은밀하게 위대하게', screenshot: 'http://t1.daumcdn.net/cfile/251E394851789C292E' },
  { value: '색계', screenshot: 'http://t1.daumcdn.net/movie/3f0592e7fef3e8c09ae96e2f0291c75a4566002a' },
  { value: '의형제', screenshot: 'http://t1.daumcdn.net/cfile/1332ED0E4B4657FF36' },
  { value: '007 스카이폴', screenshot: 'http://t1.daumcdn.net/cfile/2011A84A5073E1161B' },
  { value: '미션 임파서블: 폴아웃', screenshot: 'http://t1.daumcdn.net/movie/8a0fc02b9a3eb8869ef2682735826f60d09bd0fc' },
  { value: '메트릭스', screenshot: 'http://t1.daumcdn.net/movie/395e534d66ea43488009d52d87a3a6af1567760609800' },
  { value: '히말라야', screenshot: 'http://t1.daumcdn.net/movie/459a7ccc0cfc901d255dc1d0c8707bd02b6e5a5a' },
  { value: '터널', scriptList: [
      {
        screenshot: 'images/movie/tunnel01.png',
        script: '다 꺼져 이 개새끼들아. 라고 이분이 말씀하셨습니다.',
      },
      {
        screenshot: 'images/movie/tunnel02.png',
        script: '누구? 나? 왜?',
      },
    ]
  },
  { value: '부산행', screenshot: 'https://movie-phinf.pstatic.net/20160427_60/1461745425689JBP24_JPEG/movie_image.jpg' },
  { value: '국제시장', scriptList: [
      { screenshot: 'images/movie/globalmarket01.png', script: '여 운동장이 아이다. 놀러나온게 아이다.' },
      { screenshot: 'images/movie/globalmarket02.png', script: '아버지. 내 약속 잘 지켰지예? 막순이도 찾았고, 이만하면 내 잘 살았지예? 근데 내 진짜 힘들었거든예' }
    ] },
  { value: '트랜스포머', screenshot: 'http://t1.daumcdn.net/cfile/126F1B10AB8C7E4691' },
  { value: '늑대소년', screenshot: 'http://t1.daumcdn.net/cfile/116B164A5085EEAE1D' },
  { value: '이터널 선샤인', screenshot: 'http://t1.daumcdn.net/movie/6f004dfd2b0e90f4e5f4973a4e76d7114f772cc1' },
  { value: '사도', screenshot: 'https://movie-phinf.pstatic.net/20150716_156/1437014129392I8TO4_JPEG/movie_image.jpg' },
  { value: '웰컴 투 동막골', screenshot: 'https://movie-phinf.pstatic.net/20111222_268/1324548988315saGVc_JPEG/movie_image.jpg' },
  { value: '내 아내의 모든것', screenshot: 'https://movie-phinf.pstatic.net/20120423_299/1335166025862kFb6W_JPEG/movie_image.jpg' },
  { value: '김종욱 찾기', screenshot: 'images/movie/findkimjongguk.png' },
  { value: '전우치', screenshot: 'http://t1.daumcdn.net/cfile/1146B4264B2F33E207' },
  { value: '군도', screenshot: 'images/movie/gundo.png' },
  { value: '괴물', screenshot: 'http://t1.daumcdn.net/cfile/12110210A8B2EDB441' },
  { value: '화이: 괴물을 삼킨 아이', screenshot: 'http://t1.daumcdn.net/cfile/214858495215AB990A' },
  { value: '독전', screenshot: 'https://movie-phinf.pstatic.net/20180604_284/1528074809424DdA9C_JPEG/movie_image.jpg' },
  { value: '접속', screenshot: 'https://movie-phinf.pstatic.net/20111222_52/1324534270853gMs61_JPEG/movie_image.jpg' },
  { value: '약속', scriptList: [
      { screenshot: 'images/movie/promise.png',
        script: '당신께서 저한테... 니 죄가 무엇이냐 고 물으신다면... 이 사람을 만나고... 사랑하고... 홀로 남겨두고 떠난다는 것이 가장 큰 죄일 것입니다.' }
    ] },
  { value: '은교', screenshot: 'https://movie-phinf.pstatic.net/20120330_215/1333097862663h3pdn_JPEG/movie_image.jpg' },
  { value: '우리들의 행복한 시간', screenshot: 'https://movie-phinf.pstatic.net/20111222_44/13245617131446aDli_JPEG/movie_image.jpg' },
  { value: '뷰티 인사이드', screenshot: 'https://movie-phinf.pstatic.net/20150603_144/1433298396491dhWLD_JPEG/movie_image.jpg' },
  { value: '퍼펙트 게임', screenshot: 'https://movie-phinf.pstatic.net/20111224_230/1324654398379Mg753_JPEG/movie_image.jpg' },
  { value: '킬빌 1부', screenshot: 'https://movie-phinf.pstatic.net/20111223_74/13245830310193s8BG_JPEG/movie_image.jpg' },
  { value: '피아니스트', screenshot: 'https://movie-phinf.pstatic.net/20111223_151/1324569051618gDbvE_JPEG/movie_image.jpg' },
  { value: '엑스맨 탄생: 울버린', screenshot: 'https://movie-phinf.pstatic.net/20111223_78/1324576397382QIJbl_JPEG/movie_image.jpg' },
  { value: '물랑루즈', screenshot: 'https://movie-phinf.pstatic.net/20150217_242/14241544239486e6WD_JPEG/movie_image.jpg' },
  { value: '메멘토', screenshot: 'https://movie-phinf.pstatic.net/20111221_83/1324475874184WP9ic_JPEG/movie_image.jpg' },
  { value: '아멜리에', screenshot: 'https://movie-phinf.pstatic.net/20211130_180/1638254681852681Mn_JPEG/movie_image.jpg' },
  { value: '원스', screenshot: 'https://movie-phinf.pstatic.net/20120112_70/1326346564198hxAP5_JPEG/movie_image.jpg' },
  { value: '파이트 클럽', screenshot: 'https://movie-phinf.pstatic.net/20160920_84/1474337305472yMUGj_JPEG/movie_image.jpg' },
  { value: '슬럼독 밀리어네어', screenshot: 'https://movie-phinf.pstatic.net/20111222_229/1324553086754yGHg1_JPEG/movie_image.jpg' },
  { value: '줄무늬 파자마를 입은 소년', screenshot: '', script: '', sound: '' },
  { value: '예스맨', screenshot: '', script: '', sound: '' },
  { value: '레버넌트', screenshot: '', script: '', sound: '' },
  { value: '벤자민 버튼의 시간은 거꾸로 간다', screenshot: '', script: '', sound: '' },
  { value: '러브 엑츄얼리', screenshot: '', script: '', sound: '' },
  { value: '러브레터', screenshot: '', script: '', sound: '' },
  { value: '오펀 천사의 비밀', screenshot: '', script: '', sound: '' },
  { value: '아는 여자', screenshot: '', script: '', sound: '' },
  { value: '만추', screenshot: '', script: '', sound: '' },
  { value: '아저씨', screenshot: '', script: '', sound: '' },
  { value: '미녀는 아름다워', screenshot: '', script: '', sound: '' },
  { value: '태극기 휘날리며', screenshot: '', script: '', sound: '' },
  { value: '주유소 습격사건', screenshot: '', script: '', sound: '' },
  { value: '타이타닉', screenshot: '', script: '', sound: '' },
  { value: '우리형', screenshot: '', script: '', sound: '' },
  { value: '마더', screenshot: '', script: '', sound: '' },
  { value: '웜바디스', screenshot: '', script: '', sound: '' },
  { value: '월드워Z', screenshot: '', script: '', sound: '' },
  { value: '세 얼간이', screenshot: '', script: '', sound: '' },
  { value: '인셉션', screenshot: '', script: '', sound: '' },
  { value: '미이라', screenshot: '', script: '', sound: '' },
  { value: '슈퍼배드', screenshot: '', script: '', sound: '' },
  { value: '죽은 시인의 사회', screenshot: '', script: '', sound: '' },
  { value: '굿 윌 헌팅', screenshot: '', script: '', sound: '' },
  { value: '스타이즈 본', screenshot: '', script: '', sound: '' },
  { value: '행오버', screenshot: '', script: '', sound: '' },
  { value: '헤드윅', screenshot: '', script: '', sound: '' },
  { value: '파리넬리', screenshot: '', script: '', sound: '' },
  { value: '클래식', screenshot: '', script: '', sound: '' },
  { value: '보디가드', screenshot: '', script: '', sound: '' },
  { value: '로마의 휴일', screenshot: '', script: '', sound: '' },
  { value: '감기', screenshot: '', script: '', sound: '' },
  { value: '연가시', screenshot: '', script: '', sound: '' },
  { value: '시네마 천국', screenshot: '', script: '', sound: '' },
  { value: '사운드 오브 뮤직', screenshot: '', script: '', sound: '' },
  { value: '다빈치 코드', screenshot: '', script: '', sound: '' },
  { value: '포레스트 검프', screenshot: '', script: '', sound: '' },
  { value: '더 테러 라이브', screenshot: '', script: '', sound: '' },
  { value: '스쿨오브락', screenshot: '', script: '', sound: '' },
  { value: '말죽거리 잔혹사', scriptList: [
      { screenshot: 'images/movie/akfwnrrjfl.png', script: '야 이 개새끼야. 너 이리나와. 이 씨발놈아, 니가 그렇게 싸움을 잘해? 옥상으로 올라와' }
    ] },
  { value: '히트맨', screenshot: '', script: '', sound: '' },
  { value: '동갑내기 과외하기', screenshot: '', script: '', sound: '' },
  { value: '협상', screenshot: '', script: '', sound: '' },
  { value: '마이네임', screenshot: '', script: '', sound: '' },
  { value: '알고있지만', screenshot: '', script: '', sound: '' },
]

export const dramaList = [
  { value: '스물 다섯 스물 하나', screenshot: '', sound: '' },
  { value: '유미의 세포들', screenshot: '', script: '', sound: '' },
  { value: '부부의 세계', screenshot: '', sound: '' },
  { value: '별에서 온 그대', screenshot: '', sound: '' },
  { value: '천국의 계단', screenshot: '', sound: '' },
  { value: '동백꽃 필 무렵', screenshot: '', sound: '' },
  { value: '파스타', screenshot: '', sound: '' },
  { value: '나인', screenshot: '', sound: '' },
  { value: '로맨스가 필요해2', screenshot: '', sound: '' },
  { value: '나의 아저씨', screenshot: '', sound: '' },
  { value: '눈이 부시게', screenshot: '', sound: '' },
  { value: '시그널', screenshot: '', sound: '' },
  { value: '쌈 마이웨이', screenshot: '', sound: '' },
  { value: '이태원클라스', screenshot: '', sound: '' },
  { value: '도깨비', screenshot: '', sound: '' },
  { value: '오징어 게임', screenshot: '', sound: '' },
  { value: '지금 우리 학교는', screenshot: '', sound: '' },
  { value: '응답하라 1997', screenshot: '', sound: '' },
  { value: '응답하라 1994', screenshot: '', sound: '' },
  { value: '응답하라 1988', screenshot: '', sound: '' },
  { value: '슬기로운 의사생활', screenshot: '', sound: '' },
  { value: 'D.P', screenshot: '', sound: '' },
  { value: '호텔델루나', screenshot: '', sound: '' },
  { value: '가을동화', screenshot: '', sound: '' },
  { value: '겨울연가', screenshot: '', sound: '' },
  { value: '여름향기', screenshot: '', sound: '' },
  { value: '태양의 후예', screenshot: '', sound: '' },
  { value: '검색어를 입력하세요', screenshot: '', sound: '' },
  { value: '미안하다 사랑한다', screenshot: '', sound: '' },
  { value: '비밀의 숲', screenshot: '', sound: '' },
  { value: '파리의 연인', screenshot: '', sound: '' },
  { value: '별을 쏘다', screenshot: '', sound: '' },
  { value: '네 멋대로 해라', screenshot: '', sound: '' },
  { value: '로망스', screenshot: '', sound: '' },
  { value: '풀하우스', screenshot: '', sound: '' },
  { value: '아이리스', screenshot: '', sound: '' },
  { value: '커피프린스 1호점', screenshot: '', sound: '' },
  { value: '내이름은 김삼순', screenshot: '', sound: '' },
  { value: '대장금', screenshot: '', sound: '' },
  { value: '돌아온 일지매', screenshot: '', sound: '' },
  { value: '개와 늑대의 시간', screenshot: '', sound: '' },
  { value: '궁', screenshot: '', sound: '' },
  { value: '발리에서 생긴일', screenshot: '', sound: '' },
  { value: '하얀거탑', screenshot: '', sound: '' },
  { value: '뉴하트', screenshot: '', sound: '' },
  { value: '환상의 커플', screenshot: '', sound: '' },
  { value: '모래시계', screenshot: '', sound: '' },
  { value: '디어마이프렌즈', screenshot: '', sound: '' },
  { value: '베토벤 바이러스', screenshot: '', sound: '' },
  { value: '그들이 사는 세상', screenshot: '', sound: '' },
  { value: '거침없이 하이킥', screenshot: '', sound: '' },
  { value: '지붕뚫고 하이킥', screenshot: '', sound: '' },
  { value: '웬만해선 그들을 막을 수 없다', screenshot: '', sound: '' },
  { value: '순풍산부인과', screenshot: '', sound: '' },
  { value: '안녕프란체스카', screenshot: '', sound: '' },
  { value: '전원일기', screenshot: '', sound: '' },
  { value: '김비서가 왜그럴까', screenshot: '', sound: '' },
  { value: '뷰티 인사이드', screenshot: '', sound: '' },
  { value: '킬미힐미', screenshot: '', sound: '' },
  { value: '미생', screenshot: '', sound: '' },
  { value: '카이스트', screenshot: '', sound: '' },
  { value: '질투의 화신', screenshot: '', sound: '' },
  { value: '괜찮아 사랑이야', screenshot: '', sound: '' },
  { value: '프로듀사', screenshot: '', sound: '' },
  { value: '주군의 태양', screenshot: '', sound: '' },
  { value: '최고의 사랑', screenshot: '', sound: '' },
  { value: '건빵선생과 별사탕', screenshot: '', sound: '' },
  { value: '달콤한 나의 도시', screenshot: '', sound: '' },
  { value: '빅', screenshot: '', sound: '' },
  { value: '킹덤', screenshot: '', sound: '' },
  { value: '지옥', screenshot: '', sound: '' },
  { value: '육룡이 나르샤', screenshot: '', sound: '' },
  { value: '뿌리깊은 나무', screenshot: '', sound: '' },
  { value: '태왕사신기', screenshot: '', sound: '' },
  { value: '팬트하우스', screenshot: '', sound: '' },
  { value: '선덕여왕', screenshot: '', sound: '' },
  { value: '여인천하', screenshot: '', sound: '' },
  { value: '고백부부', screenshot: '', sound: '' },
  { value: '그 해 우리는', screenshot: '', sound: '' },
  { value: '스카이캐슬', screenshot: '', sound: '' },
  { value: '빈센조', screenshot: '', sound: '' },
  { value: '경이로운 소문', screenshot: '', sound: '' },
  { value: '힘쎈여자 도봉순', screenshot: '', sound: '' },
  { value: '스위트 홈', screenshot: '', sound: '' },
  { value: '시크릿 가든', screenshot: '', sound: '' },
  { value: '추노', screenshot: '', sound: '' },
  { value: '동이', screenshot: '', sound: '' },
  { value: '대장금', screenshot: '', sound: '' },
  { value: '이산', screenshot: '', sound: '' },
  { value: '공부의 신', screenshot: '', sound: '' },
  { value: '드림하이', screenshot: '', sound: '' },
  { value: '간 떨어지는 동거', screenshot: '', sound: '' },
  { value: '성균관 스캔들', screenshot: '', sound: '' },
  { value: '재빵왕 김탁구', screenshot: '', sound: '' },
  { value: '아내의 유혹', screenshot: '', sound: '' },
  { value: '신기생뎐', screenshot: '', sound: '' },
  { value: '푸른 바다의 전설', screenshot: '', sound: '' },
  { value: '라이브', screenshot: '', sound: '' },
  { value: '탐정', screenshot: '', sound: '' },
  { value: '브레인', screenshot: '', sound: '' },
  { value: '빠담빠담', screenshot: '', sound: '' },
  { value: '해를 품은 달', screenshot: '', sound: '' },
  { value: '신사의 품격', screenshot: '', sound: '' },
  { value: '넝쿨째 굴러온 당신', screenshot: '', sound: '' },
  { value: '각시탈', screenshot: '', sound: '' },
  { value: '또 오해영', screenshot: '', sound: '' },
  { value: '그 겨울, 바람이 분다', screenshot: '', sound: '' },
  { value: '논스톱', screenshot: '', sound: '' },
  { value: '너의 목소리가 들려', screenshot: '', sound: '' },
  { value: '피노키오', screenshot: '', sound: '' },
  { value: '알함브라 궁전의 추억', screenshot: '', sound: '' },
  { value: '스타트업', screenshot: '', sound: '' },
]

export const musicList = [
  { singer: '소녀시대', music: '소원을 말해봐', youtube_id: '5khS_KwMC_g' },
  { singer: '소녀시대', music: 'kissing u', youtube_id: 'RZwxxqmhA7c' },
  { singer: '소녀시대', music: '다시만난세계', youtube_id: 'mbg1Cn6Ua9U' },
  { singer: '소녀시대', music: 'Gee', youtube_id: 'qizghQs4K6E' },
  { singer: '소녀시대', music: '힘내', youtube_id: 'Hi1P7LTshM' },
  { singer: '소녀시대', music: 'Oh', youtube_id: '5r6M-c3_7YA' },
  { singer: '성시경', music: '너의 모든 순간', youtube_id: 'IQEDU7SZI2Y' },
  { singer: '성시경', music: '희재', youtube_id: 'nD1p_H3qo_A' },
  { singer: '성시경', music: '넌 감동이었어', youtube_id: 'yPzSRKbjnCw' },
  { singer: '성시경', music: '태양계', youtube_id: 'lCOiahfnNIw' },
  { singer: '성시경', music: '너는 나의 봄이다', youtube_id: '93SsG6D78XI' },
  { singer: '성시경', music: '한번 더 이별', youtube_id: 'WpfWKRpWD6g' },
  { singer: '성시경', music: '너에게', youtube_id: 'YE9YnrFgib8' },
  { singer: '성시경', music: '차마', youtube_id: 'SR29CCtJGJ4' },
  { singer: '성시경', music: '거리에서', youtube_id: 'wcuWIz6CI1U' },
  { singer: '블락비', music: 'Toy', youtube_id: 'RAcY9IyAs0M' },
  { singer: '블락비', music: 'Her', youtube_id: 'g4pDuadNyzo' },
  { singer: 'WINNER', music: 'Really Really', youtube_id: 'aYlXNpaQydk' },
  { singer: 'WINNER', music: '공허해', youtube_id: 'zTAUu-B0k80' },
  { singer: 'WINNER', music: '끼부리지마', youtube_id: 'gq5kNO5uG-8' },
  { singer: '세븐', music: '와줘', youtube_id: '9vpTUcFb1J8' },
  { singer: '세븐', music: '열정', youtube_id: 'Cqokr695Gic' },
  { singer: '박화요비', music: '그런일은', youtube_id: 'lVYLj8GNNyw' },
  { singer: '박화요비', music: '어떤가요', youtube_id: '-EtHD_aLrfo' },
  { singer: '박화요비', music: '당신과의 키스를 세어보아요', youtube_id: 'hNiTVOjpfRE' },
  { singer: '박화요비', music: 'Lie', youtube_id: '91nYFfqt7HQ' },
  { singer: '앤 원', music: '혼자하는 사랑', youtube_id: '2PVULzeTXdI' },
  { singer: '앤 원', music: '아프고 아픈 이름', youtube_id: '4CGlHJkv404' },
  { singer: '젝스키스', music: '커플', youtube_id: 'hPu72MUS5aY' },
  { singer: '젝스키스', music: '예감', youtube_id: 'EaJYebDQMcI' },
  { singer: '젝스키스', music: '사나이가는(부제/폼생폼사)', youtube_id: 'flW01iDpmnM' },
  { singer: '핑클', music: '영원한 사랑', youtube_id: 'xw2I0MO3P60' },
  { singer: '핑클', music: '내 남자 친구에게', youtube_id: 'YI8n7WYhU9E' },
  { singer: '핑클', music: 'Now', youtube_id: '0zoY7T7jLpY' },
  { singer: '핑클', music: '영원', youtube_id: 'hKQgKhWAdok' },
  { singer: '핑클', music: '화이트', youtube_id: 'azfvnow' },
  { singer: '핑클', music: '늘 지금처럼', youtube_id: '-0tYSbrlNoE' },
  { singer: 'S.E.S', music: 'Dreams Come True', youtube_id: 'pJWUwPPcbqA' },
  { singer: 'S.E.S', music: '꿈을 모아서', youtube_id: '3LUmDZz2m04' },
  { singer: 'S.E.S', music: '너를 사랑해', youtube_id: 'LKr3kSirJr4' },
  { singer: 'S.E.S', music: 'I\'m Your Girl', youtube_id: 'cdjW5HK3TrE' },
  { singer: 'S.E.S', music: '너를 사랑해', youtube_id: 'LKr3kSirJr4' },
  { singer: 'S.E.S', music: 'Just A Feeling', youtube_id: '7j8fpjTHkUY' },
  { singer: 'S.E.S', music: '달리기', youtube_id: 'Uh-OoxxkMdM' },
  { singer: '베이비복스', music: 'Get Up', youtube_id: 'dIHrTkvELJU' },
  { singer: '베이비복스', music: 'Killer', youtube_id: 'jGfXiBnxScI' },
  { singer: '베이비복스', music: '야야야', youtube_id: 'BK_mEPTrySE' },
  { singer: '베이비복스', music: '우연', youtube_id: 'y8wtQ5Xgwvk' },
  { singer: '베이비복스', music: '인형', youtube_id: '6WNTC0lDJz0' },
  { singer: '베이비복스', music: 'Why', youtube_id: '26mEU0PEFxc' },
  { singer: 'Red Velvet', music: 'Feel My Rhythm', youtube_id: 'OXWz_x6-dro' },
  { singer: 'Red Velvet', music: 'Psycho', youtube_id: 'PyyT5tHbOLw' },
  { singer: 'Red Velvet', music: '피카부 (Peek-A-Boo)', youtube_id: 'jxM5V0FBxFs' },
  { singer: 'Red Velvet', music: '빨간 맛 Red Flavor', youtube_id: 'BLavT7w4R9I' },
  { singer: 'Red Velvet', music: 'Power Up', youtube_id: 'oyqU1BjuK6A' },
  { singer: 'Red Velvet', music: 'Dumb Dumb', youtube_id: 'EXknw6fStAs' },
  { singer: 'Red Velvet', music: 'Ice Cream Cake', youtube_id: 'bJ-B2BNdEFs' },
  { singer: 'BTS', music: 'Dynamite', youtube_id: 'HaEYUJ2aRHs' },
  { singer: 'BTS', music: 'Butter', youtube_id: 'XRvghkaRF-Y' },
  { singer: 'BTS', music: '작은 것들을 위한 시', youtube_id: 'Q-erYa8cwnc' },
  { singer: 'BTS', music: '피 땀 눈물', youtube_id: 'tuEZ_8HdnwQ' },
  { singer: 'BTS', music: '봄날', youtube_id: 'ZO1xdXOXarc' },
  { singer: 'BTS', music: 'Run', youtube_id: 'LYUCYSszl7w' },
  { singer: 'EXO', music: 'Love shot', youtube_id: 'KmRqHwJrTKQ' },
  { singer: 'EXO', music: 'Monster', youtube_id: 'KJevaDSz7Nc' },
  { singer: 'EXO', music: '으르렁', youtube_id: 'sSEuY7PB4Cc' },
  { singer: '아이유(IU)', music: 'Celebrity', youtube_id: 'es6bbfAjk3I' },
  { singer: '아이유(IU)', music: '내 손을 잡아', youtube_id: 'r_-GQjN9Tpc' },
  { singer: '아이유(IU)', music: '삐삐', youtube_id: 'BZqfL_2CzKg' },
  { singer: '아이유(IU)', music: '스물셋', youtube_id: 'GXNHaLIhyMY' },
  { singer: '아이유(IU)', music: '금요일에 만나요', youtube_id: 'xKZ3U8viuIU' },
  { singer: '아이유(IU)', music: '너랑 나', youtube_id: 'seFr4qWykgY' },
  { singer: '아이유(IU)', music: '팔레트', youtube_id: '2C1Jg04INb4' },
  { singer: '아이유(IU)', music: '잔소리', youtube_id: 'bzdsqPOJK_I' },
  { singer: '아이유(IU)', music: '밤편지', youtube_id: 'NnRjwEhFU70' },
  { singer: '아이유(IU)', music: '하루 끝', youtube_id: 'gJtNx3P02Z4' },
  { singer: '아이유(IU)', music: '분홍신', youtube_id: 'C-Mxyvv0IDY' },
  { singer: '아이유(IU)', music: '이름에게', youtube_id: 'JSOBF_WhqEM' },
  { singer: '이효리', music: 'U-Go-Girl (유고걸)', youtube_id: 'z246K3KBZjo' },
  { singer: '이효리', music: '10 Minutes', youtube_id: 'okJnl6n3G7E' },
  { singer: '이효리', music: 'Bad Girls', youtube_id: 'iQnGdZCt5gQ' },
  { singer: '이효리', music: 'Chitty Chitty Bang Bang', youtube_id: 'X-KPWhROsNY' },
  { singer: '박효신', music: '바보', youtube_id: 'R8ufINMmWxY' },
  { singer: '박효신', music: '야생화', youtube_id: 'zGZAyXktNqg' },
  { singer: '박효신', music: '눈의 꽃', youtube_id: 'AqwyuF0Rp8k' },
  { singer: '박효신', music: '사랑한 후에', youtube_id: '7c3wuDMuCkk' },
  { singer: '박효신', music: '추억은 사랑을 닮아', youtube_id: 'KaOzQqE-fwQ' },
  { singer: '박효신', music: '좋은사람', youtube_id: 'DFAP0w7CasQ' },
  { singer: '린', music: '...사랑했잖아...', youtube_id: 'nj_6geqNPLA' },
  { singer: '린', music: 'My Destiny', youtube_id: 'll7iWEYR5jA' },
  { singer: '린', music: '시간을 거슬러', youtube_id: '2CPhSQ_sq3k' },
  { singer: '린', music: '바람에 머문다', youtube_id: '2CPhSQ_sq3k' },
  { singer: '린', music: '곰인형', youtube_id: 'wgzQzSRd63s' },
  { singer: '케이윌', music: 'Love Blossom(러브블러썸)', youtube_id: 'jaeE4rY3aOI' },
  { singer: '케이윌', music: '말해! 뭐해?', youtube_id: 'DuPkqQ0gv8E' },
  { singer: '케이윌', music: '내 생에 아름다운', youtube_id: 'N4RAUQAQC5k' },
  { singer: '케이윌', music: '그립고 그립고 그립다', youtube_id: 'QN-H-f2dfzU' },
  { singer: '엠씨더맥스', music: '잠시만 안녕', youtube_id: '7fHYE8BI9kc' },
  { singer: '엠씨더맥스', music: 'One Love', youtube_id: 'q0Bc1lmn5fA' },
  { singer: '엠씨더맥스', music: '사계 (하루살이)', youtube_id: 'FZq-0Omm22s' },
  { singer: '엠씨더맥스', music: '행복하지 말아요', youtube_id: 'FwbEtCtz8Qk' },
  { singer: '엠씨더맥스', music: '사랑은 아프려고 하는 거죠', youtube_id: 'Mt1TtdyZ4lg' },
  { singer: '엠씨더맥스', music: '그대는 눈물겹다', youtube_id: 'DzKt097lDWk' },
  { singer: '장기하', music: '부럽지가 않어', youtube_id: 'weWl2wQNW9g' },
  { singer: '장기하', music: '싸구려 커피', youtube_id: 'LwSnYGXZ808' },
  { singer: '장기하', music: '그렇고 그런 사이', youtube_id: 'uhcyqvuOYqk' },
  { singer: 'IVE (아이브)', music: 'LOVE DIVE', youtube_id: 'hh5GKVa8VtM' },
  { singer: 'IVE (아이브)', music: 'ELEVEN', youtube_id: '0EK_M2taRIM' },
  { singer: '걸스데이', music: 'Something', youtube_id: 'y88gLc4AihI' },
  { singer: '걸스데이', music: '기대해', youtube_id: '8MVonuM0aIk' },
  { singer: '걸스데이', music: 'Darling', youtube_id: 'rGX06ES0Yek' },
  { singer: '걸스데이', music: '링마벨', youtube_id: 'ZeBX7y0Djds' },
  { singer: '걸스데이', music: '반짝반짝', youtube_id: 'J9q6b1mA7vQ' },
  { singer: '러블리즈', music: 'Ah-Choo', youtube_id: 'BzGAGdEdYYw' },
  { singer: 'OH MY GIRL', music: 'Dun Dun Dance', youtube_id: 'wkVlb8rSies' },
  { singer: 'OH MY GIRL', music: '살짝 설렜어 (Nonstop)', youtube_id: 'ztmOmJrTF5c' },
  { singer: 'OH MY GIRL', music: 'Dolphin', youtube_id: '4JJFrjkRxmo' },
  { singer: 'OH MY GIRL', music: 'Real Love', youtube_id: 'GjOxSJgI47I' },
  { singer: 'BIGBANG', music: '뱅뱅뱅 (BANG BANG BANG)', youtube_id: 'r_6ekIR_OQo' },
  { singer: 'BIGBANG', music: 'LOSER', youtube_id: '0l_NZphW4dU' },
  { singer: 'BIGBANG', music: '하루하루', youtube_id: 'c84VnpGFbrw' },
  { singer: 'BIGBANG', music: '거짓말', youtube_id: 'Y4RmVcKav9Q' },
  { singer: 'BIGBANG', music: '마지막 인사', youtube_id: 'VT9lKAPWG5E' },
  { singer: 'BIGBANG', music: '붉은 노을', youtube_id: 'UJn-F2kPCaQ' },
  { singer: '보아', music: 'Better', youtube_id: 'O0sA6Dml54I' },
  { singer: '보아', music: 'Only One', youtube_id: 'Xe-PbDRIsvE' },
  { singer: '보아', music: 'NO.1', youtube_id: '0bHHPkJIxiU' },
  { singer: '보아', music: '아틀란티스 소녀', youtube_id: 'rVF-F_bgIEc' },
  { singer: '보아', music: 'My Name', youtube_id: 'BkO1xDybJO4' },
  { singer: '보아', music: 'Girls On Top', youtube_id: 'Ev7m870Xwng' },
  { singer: '보아', music: 'ID;Peace B', youtube_id: 'xLlPM9mRlpY' },
  { singer: 'Got the beat', music: 'Step Back', youtube_id: 'zspA0I7xme4' },
  { singer: 'ITZY', music: 'WANNABE', youtube_id: 'xgiN9zNZCuM' },
  { singer: 'ITZY', music: '달라달라', youtube_id: 'miqQAzOXPBo' },
  { singer: 'ITZY', music: 'Not Shy', youtube_id: 'nTQgVDB7VOA' },
  { singer: 'TWICE', music: 'The Feels', youtube_id: 'pQBntSH-qFA' },
  { singer: 'TWICE', music: 'I CAN\'T STOP ME', youtube_id: '3d-D5bLDZSk' },
  { singer: 'TWICE', music: 'FANCY', youtube_id: 'j4OrZV_GAsI' },
  { singer: 'TWICE', music: 'Alcohol-Free', youtube_id: 'm8CyyxWgNd8' },
  { singer: 'TWICE', music: 'CHEER UP', youtube_id: 'prWVZFgZ3Zc' },
  { singer: 'TWICE', music: 'YES or YES', youtube_id: '3AIII5SN0N0' },
  { singer: 'TWICE', music: 'MORE & MORE', youtube_id: '8yTxNtVr_d8' },
  { singer: 'TWICE', music: 'OOH-AHH하게', youtube_id: '6KMN61Zsd58' },
  { singer: 'TWICE', music: 'KNOCK KNOCK', youtube_id: 'mYBpyKEcAa8' },
  { singer: 'BLACKPINK', music: 'Lovesick Girls', youtube_id: 'D8RZbI1jfQ0' },
  { singer: 'BLACKPINK', music: '붐바야', youtube_id: '18nDrsoii5M' },
  { singer: 'BLACKPINK', music: '마지막처럼', youtube_id: '9MbXeqCbS4Q' },
  { singer: 'BLACKPINK', music: '불장난', youtube_id: 'ei0k_1Uro-U' },
  { singer: 'BLACKPINK', music: '휘파람', youtube_id: 'x0-q6-PBpPU' },
  { singer: 'BLACKPINK', music: 'Kill This Love', youtube_id: 'Il_KNBTmLpQ' },
  { singer: 'BLACKPINK', music: '뚜두뚜두', youtube_id: 'IPzouyj7FLA' },
  { singer: 'aespa', music: 'Savage', youtube_id: 'REmUidcJt5I' },
  { singer: 'aespa', music: 'Next Level', youtube_id: 'tkzYyEp4zB4' },
  { singer: 'aespa', music: 'Black Mamba', youtube_id: 'BL-aIpCLWnU' },
  { singer: '제시(Jessi)', music: '눈누난나', youtube_id: 'ch-b-pfz30U' },
  { singer: '제시(Jessi)', music: '어떤X What Type of X', youtube_id: 'hJ7reUmIIaM' },
  { singer: '제시(Jessi)', music: 'ZOOM', youtube_id: 'KXLCwmBVvwY' },
  { singer: '제시(Jessi)', music: 'Gucci', youtube_id: 'dfPv2zv4ykQ' },
  { singer: 'MC몽', music: '너에게 쓰는 편지(feat. LYn)', youtube_id: 'nhuFm3BGIBY' },
  { singer: 'MC몽', music: 'I Love U Oh Thank U(feat. 김태우)', youtube_id: 'KUi3kGl5Jbg' },
  { singer: 'MC몽', music: '아이스크림', youtube_id: 'm73EFJZRe4A' },
  { singer: '비(RAIN)', music: '깡 GANG', youtube_id: '8B8lFCJOerM' },
  { singer: '비(RAIN)', music: 'It′s Raining', youtube_id: 'nueYr7Yx8CU' },
  { singer: '비(RAIN)', music: 'I Do', youtube_id: 'dMH5qitbxsk' },
  { singer: '비(RAIN)', music: '태양을 피하는 방법', youtube_id: 'GoT3vK3zrPE' },
  { singer: '비(RAIN)', music: '안녕이란 말 대신', youtube_id: 'neTb1mB_7j4' },
  { singer: '비(RAIN)', music: '나쁜 남자 Bad Man', youtube_id: 'z3Kdgd6Vqq4' },
  { singer: '헤이즈', music: '비도 오고 그래서', youtube_id: 'hGWMhVbaJNg' },
  { singer: '헤이즈', music: '널 너무 모르고', youtube_id: 'T1wssdlybp4' },
  { singer: '헤이즈', music: '돌아오지마', youtube_id: 'I7EwLNhPgpg' },
  { singer: '헤이즈', music: 'HAPPEN (헤픈 우연)', youtube_id: '_2Q9yS3TDcw' },
  { singer: 'god', music: '길', youtube_id: '_EgZ9sfrCf8' },
  { singer: 'god', music: '촛불하나', youtube_id: 'Llg91lVmctg' },
  { singer: 'god', music: '거짓말', youtube_id: 'Cq1z_7eWEv4' },
  { singer: 'god', music: '사랑해 그리고 기억해', youtube_id: 'BC5vQCuqWw8' },
  { singer: 'god', music: '다시', youtube_id: 'B5P3NGFrmJg' },
  { singer: 'god', music: '하늘색 풍선', youtube_id: 'ysWlLG8AbUw' },
  { singer: 'god', music: '어머님께', youtube_id: '1Vleb1kqpZg' },
  { singer: 'god', music: '니가 있어야 할 곳', youtube_id: '1XC_SItrOBY' },
  { singer: 'H.O.T', music: '캔디', youtube_id: 'BaQDN_Ex9L4' },
  { singer: 'H.O.T', music: '빛', youtube_id: 'Ls2rKrCjbqU' },
  { singer: 'H.O.T', music: '행복', youtube_id: 'VBqu26E-K20' },
  { singer: 'H.O.T', music: 'We are the future', youtube_id: 'jvN8q1zrAWc' },
  { singer: 'H.O.T', music: '전사의 후예', youtube_id: 'RpGTUmISOyg' },
  { singer: 'H.O.T', music: '아이야', youtube_id: 'jRaDeILxH58' },
  { singer: '신화', music: 'Perfect Man', youtube_id: 'AOs80sevyHw' },
  { singer: '신화', music: 'Brand New', youtube_id: '6a5vdG-HigY' },
  { singer: '신화', music: 'I Pray 4 U', youtube_id: 'D-Fk5StrdTc' },
  { singer: '신화', music: 'T.O.P. Twinkling of paradise', youtube_id: 'kE9TXY4gazk' },
  { singer: '신화', music: 'Wild Eyes', youtube_id: 'uLXp7Vv7sNE' },
  { singer: '신화', music: '으쌰! 으쌰!', youtube_id: 'wnCZ0kRJRaQ' },
  { singer: '동방신기', music: 'Hug', youtube_id: '6cniFwhVV_U' },
  { singer: '동방신기', music: '주문 MIROTIC', youtube_id: 'Z9Lh6WCl5e8' },
  { singer: '슈퍼주니어', music: '쏘리 쏘리 Sorry, Sorry', youtube_id: '_rX0IoeMSoc' },
  { singer: '규현', music: '광화문에서', youtube_id: 'GAdFpZHTh1I' },
  { singer: 'SHINee', music: 'Don\'t Call Me', youtube_id: 'wSsQmJmydrI' },
  { singer: 'SHINee', music: 'Ring Ding Dong', youtube_id: 'i_eaPKbm00Q' },
  { singer: 'SHINee', music: '누난 너무 예뻐 Replay', youtube_id: 'GOVuu27dZCI' },
  { singer: 'SHINee', music: 'Lucifer', youtube_id: 'xFHAcsUXc-c' },
  { singer: 'SHINee', music: '산소같은 너', youtube_id: '4WJ-NkyFqSY' },
  { singer: 'SHINee', music: 'Sherlock·셜록(Clue + Note)', youtube_id: '3v8m-fpCszs' },
  { singer: '코요태', music: '실연', youtube_id: 'nmDfw5oUQAk' },
  { singer: '코요태', music: '파란', youtube_id: '6X4DwACIZtA' },
  { singer: '코요태', music: '순정', youtube_id: 'CHiizjoys1Q' },
  { singer: '코요태', music: '비몽', youtube_id: 'fZ1K22F4Ouo' },
  { singer: '에픽하이', music: '우산', youtube_id: 'Wbb7fWQjz4c' },
  { singer: '에픽하이', music: 'One', youtube_id: 'OKsqczjP5-8' },
  { singer: '에픽하이', music: 'Fly', youtube_id: 'sHqLlyBlmQI' },
  { singer: '에픽하이', music: '1분 1초', youtube_id: 'KFZ4nrBDyPM' },
  { singer: '에픽하이', music: '빈차', youtube_id: '6U2h_iccLXE' },
  { singer: '에픽하이', music: 'Fan', youtube_id: 'z7pwbKt46FY' },
  { singer: '배치기', music: '마이동풍', youtube_id: 'fNAzj6vW4cQ' },
  { singer: '배치기', music: '눈물샤워', youtube_id: '7-YujWTeWVw' },
  { singer: '45RPM', music: '즐거운 생활', youtube_id: 'ufmlG8hPLWY' },
  { singer: '정기고', music: '썸', youtube_id: 'sONklohp9Wo' },
  { singer: '산이', music: '아는사람 얘기', youtube_id: 'RF32rudhICE' },
  { singer: '산이', music: '한 여름밤의 꿀', youtube_id: 'FWZoL39oFlQ' },
  { singer: '클래지콰이', music: 'She Is', youtube_id: 'zjVt73gD1fc' },
  { singer: '클래지콰이', music: 'Sweety', youtube_id: 'xp7zmlkgWh8' },
  { singer: '클래지콰이', music: '러브 레시피', youtube_id: 'tSo0gnO8P0w' },
  { singer: '클래지콰이', music: 'Romeo N Juliet', youtube_id: '9tsYDZEiNdg' },
  { singer: '이소라', music: '바람이 분다', youtube_id: 'Fk__GLYSFMw' },
  { singer: '이소라', music: 'Track 9', youtube_id: 'MjQjaB-HedA' },
  { singer: '이소라', music: 'Track 8', youtube_id: '3RTm-_RQ-lo' },
  { singer: '이소라', music: '청혼', youtube_id: '7UF9xujJwGo' },
  { singer: '이소라', music: '나를 사랑하지 않는 그대에게', youtube_id: '0w9pTifeGMs' },
  { singer: '이소라', music: '처음 느낌 그대로', youtube_id: '063bjQ9j_rI' },
  { singer: '이소라', music: '제발', youtube_id: 'HBkzuPJnrVI' },
  { singer: '리쌍', music: 'Ballerino', youtube_id: 'd1sXqVAh2CY' },
  { singer: '리쌍', music: '헤어지지 못하는 여자, 떠나가지 못하는 남자', youtube_id: 'cPtvGVLuJYo' },
  { singer: '리쌍', music: '광대', youtube_id: 'OJhA9nOXMWw' },
  { singer: '리쌍', music: '내가 웃는게 아니야', youtube_id: 'kQQmD9iAQl8' },
  { singer: '리쌍', music: 'TV를 껐네...', youtube_id: 'OBcEwt1uZsU' },
  { singer: '리쌍', music: '우리 지금 만나', youtube_id: '0TGyc5NfEkc' },
  { singer: '리쌍', music: 'Rush', youtube_id: '1t5OU0GODXk' },
  { singer: '리즈', music: '그댄 행복에 살텐데', youtube_id: 'MkE_MtsicxQ' },
  { singer: '페이지', music: '이별이 오지 못하게', youtube_id: 'mIA_lez1Db4' },
  { singer: '페이지', music: '난 늘 혼자였죠', youtube_id: 'wjTrNgb-Bro' },
  { singer: '오윤혜', music: 'I Wish', youtube_id: 'qSe1eeQk4EI' },
  { singer: '김범수', music: '보고 싶다', youtube_id: 'Nl-iaDdA908' },
  { singer: '김범수', music: '끝사랑', youtube_id: 'OmszNg2R_f8' },
  { singer: '김범수', music: '하루', youtube_id: 'EouXSoZrJbE' },
  { singer: '김범수', music: '슬픔활용법', youtube_id: 'Ty4Amy19hk8' },
  { singer: '바이브', music: '그 남자 그 여자', youtube_id: '2RMs8I3LUd4' },
  { singer: '바이브', music: '미친거니', youtube_id: '1Z_U1pube1U' },
  { singer: '바이브', music: '미워도 다시 한번', youtube_id: 'FMFBL8HtIFs' },
  { singer: '바이브', music: '사진을 보다가', youtube_id: '67aGCYNwcqk' },
  { singer: '엄정화', music: 'Poison', youtube_id: 'yMZe3nYA6dY' },
  { singer: '엄정화', music: '초대', youtube_id: 'XyMSZjmCrKM' },
  { singer: '엄정화', music: 'Festival', youtube_id: 'O63yDNWiFWY' },
  { singer: '엄정화', music: '배반의 장미', youtube_id: 'Iwc1lyTDCjg' },
  { singer: '엄정화', music: '몰라', youtube_id: '5VmQ5ReoDDI' },
  { singer: '엄정화', music: 'D.I.S.C.O', youtube_id: 'C0USKQRvuIc' },
  { singer: '이정현', music: '와', youtube_id: 'ZblHv1Lpyfk' },
  { singer: '이정현', music: '바꿔', youtube_id: 'NY-U-0NHccs' },
  { singer: '이정현', music: '반', youtube_id: 'spJqFVUopL8' },
  { singer: '이정현', music: '미쳐', youtube_id: 'bh3ypKFDwME' },
  { singer: '김현정', music: '멍', youtube_id: 'peN6nMZluVM' },
  { singer: '김현정', music: '혼자한 사랑', youtube_id: '0Idy34Yl_Wg' },
  { singer: '김현정', music: '되돌아온 이별', youtube_id: 'HF3F15nCmK4' },
  { singer: '김현정', music: '그녀와의 이별', youtube_id: 'UxJugDFKdK4' },
  { singer: '소찬휘', music: 'Tears', youtube_id: 'gRV8pMtyzvI' },
  { singer: '소찬휘', music: '현명한 선택', youtube_id: 'QiPNNUKXMSk' },
  { singer: '소찬휘', music: 'Fine', youtube_id: '00SVerdH12A' },
  { singer: '서문탁', music: '사랑, 결코 시들지 않는....', youtube_id: 'R3IzccqqBKk' },
  { singer: '서문탁', music: '사슬', youtube_id: 'ywEJZV_iCq0' },
  { singer: '서문탁', music: '사미인곡', youtube_id: 'Uaau3JFC0HU' },
  { singer: '체리필터', music: '낭만 고양이', youtube_id: 'h3XVYav2SQs' },
  { singer: '체리필터', music: '오리 날다', youtube_id: 'FYjWDBEA76E' },
  { singer: '체리필터', music: '달빛 소년', youtube_id: 'g4tJZSlIAYs' },
  { singer: '크러쉬', music: 'Oasis', youtube_id: 'dYwWCUsIKbI' },
  { singer: '크러쉬', music: 'Beautiful', youtube_id: 'to_5UOAINLY' },
  { singer: '크러쉬', music: '잊어버리지마', youtube_id: 'Aon-n3hLSto' },
  { singer: '크러쉬', music: '가끔', youtube_id: 'YVWzxPuVKmY' },
  { singer: '크러쉬', music: '나빠', youtube_id: 'eKuYN8nYIFk' },
  { singer: '크러쉬', music: '자나깨나', youtube_id: 'L4dQ820WhPY' },
  { singer: '크러쉬', music: 'SOFA', youtube_id: 'cb6RNAkQU5g' },
  { singer: '토이', music: '뜨거운 안녕', youtube_id: 'C10WwJafiCY' },
  { singer: '토이', music: '여전히 아름다운지', youtube_id: 'nuAiFzEkFZM' },
  { singer: '토이', music: '좋은 사람', youtube_id: 'jIbUJejAAyQ' },
  { singer: '토이', music: '세사람', youtube_id: 'ySHBMvse8aE' },
  { singer: '토이', music: '오늘 서울은 하루종일 맑음', youtube_id: 'JeP2oeeYqFk' },
  { singer: '토이', music: '거짓말 같은 시간', youtube_id: 'v_3HKVEdLPw' },
  { singer: '토이', music: '스케치북', youtube_id: 'E9LnoXOWXkY' },
  { singer: '토이', music: '내가 너의 곁에 잠시 살았다는 걸', youtube_id: 'j2PTEERB5Vk' },
  { singer: '롤러코스터', music: '습관', youtube_id: 'qvh74fT4xYY' },
  { singer: '윤종신', music: '좋니', youtube_id: 'oDOVv8qCREk' },
  { singer: '윤종신', music: '내일 할 일', youtube_id: 'R6JYKmuas34' },
  { singer: '윤종신', music: '오래전 그날', youtube_id: '7NCrFgFZveA' },
  { singer: '윤종신', music: '1월부터 6월까지', youtube_id: 'muDG4qOVvdc' },
  { singer: '윤종신', music: '말꼬리', youtube_id: '1kdJ012q6g8' },
  { singer: '윤종신', music: '환생', youtube_id: '-f-bGrnh0Xo' },
  { singer: '윤종신', music: '고요', youtube_id: '3sZKMq1OUy8' },
  { singer: '윤종신', music: '동네 한 바퀴', youtube_id: 'sskotm4_wiQ' },
  { singer: '에프터스쿨', music: 'DIVA', youtube_id: 'CveilV83S7U' },
  { singer: '에프터스쿨', music: 'Bang', youtube_id: 'OKwcDZtFofk' },
  { singer: '에프터스쿨', music: 'AH', youtube_id: 'fMwxbbmiwAk' },
  { singer: '티아라', music: 'T.T.L (Time To Love)', youtube_id: 'HKuMchHwUVI' },
  { singer: '티아라', music: '너 때문에 미쳐', youtube_id: 'dEifR8ewFAQ' },
  { singer: '티아라', music: 'Roly-Poly', youtube_id: 'PwpFx1-4BI4' },
  { singer: '티아라', music: 'Bo Peep Bo Peep', youtube_id: '9hJKq7nM4Ec' },
  { singer: '티아라', music: 'Lovey-Dovey', youtube_id: 'Q52lkbNsVd4' },
  { singer: '티아라', music: 'Sexy Love', youtube_id: 'vQKxrbaSAA4' },
  { singer: '별', music: 'I Think I', youtube_id: 'FRFJ-tr9enE' },
  { singer: '별', music: '안부', youtube_id: 'nVP-TrxRS9M' },
  { singer: '별', music: '12월 32일', youtube_id: 'l_2pu6P7MB4' },
  { singer: '2PM', music: '우리집', youtube_id: 'rJxNKKOuiAE' },
  { singer: '2PM', music: 'Again & Again', youtube_id: 'fByZ7AbasQw' },
  { singer: '2PM', music: '10점 만점에 10점', youtube_id: 'lqfbYfWeNhc' },
  { singer: '2PM', music: 'Heartbeat', youtube_id: 'YhMFInv1Clc' },
  { singer: '2AM', music: '죽어도 못 보내', youtube_id: 'UgdSKc933Ic' },
  { singer: '2AM', music: '이노래', youtube_id: 'TTpvoSN5LHg' },
  { singer: '원더걸스', music: 'Nobody', youtube_id: 'N9SNUWlsCVs' },
  { singer: '원더걸스', music: 'Tell me', youtube_id: '0wX6er00xrE' },
  { singer: '원더걸스', music: 'So Hot', youtube_id: 'agL-oiDlyYo' },
  { singer: '박진영', music: 'When We Disco', youtube_id: '0Z9Li1g-oUc' },
  { singer: '박진영', music: '어머님이 누구니', youtube_id: 'vetSM4axbyQ' },
  { singer: '박진영', music: '날 떠나지마', youtube_id: 'P84Mr6oPe_k' },
  { singer: '박진영', music: '대낮에 한 이별', youtube_id: 'URk3iixI0H0' },
  { singer: '박진영', music: 'Honey', youtube_id: 'T9eTQyV1fS0' },
  { singer: '박진영', music: '너의 뒤에서', youtube_id: 'a_rIXbD-dXo' },
  { singer: '박진영', music: 'Swing Baby', youtube_id: 'KVFiva6mT64' },
  { singer: '김건모', music: '잘못된 만남', youtube_id: 'n2AsXQtK8aA' },
  { singer: '김건모', music: '잠 못 드는 밤 비는 내리고', youtube_id: 'llY4UtFtrgM' },
  { singer: '김건모', music: '서울의 달', youtube_id: 'PkkPAEHHv58' },
  { singer: '김건모', music: '미안해요', youtube_id: 'rC_vLGpo3Sw' },
  { singer: '김건모', music: '사랑이 떠나가네', youtube_id: 'UauO9Jj_yDc' },
  { singer: '박혜경', music: '고백', youtube_id: 'LnwHKkmLfpQ' },
  { singer: '박혜경', music: '너에게 주고 싶은 세 가지', youtube_id: 'gngljCSP5m8' },
  { singer: '박혜경', music: '주문을 걸어', youtube_id: 'jw0E5W5BTKs' },
  { singer: '러브홀릭', music: '인형의 꿈', youtube_id: '46ZBwgVmEWs' },
  { singer: '러브홀릭', music: '그대만 있다면', youtube_id: 'hD3G8se5EIA' },
  { singer: '러브홀릭', music: 'Loveholic', youtube_id: 'TJCL8b7ufKo' },
  { singer: '자우림', music: '스물다섯, 스물하나', youtube_id: 'Ts20_7v14ZA' },
  { singer: '자우림', music: '미안해 널 미워해', youtube_id: 'rBa4ZYxI4vM' },
  { singer: '자우림', music: '매직 카펫 라이드', youtube_id: 'kUlMiYseY_U' },
  { singer: '자우림', music: '하하하쏭', youtube_id: 'fqoY2Hf-quk' },
  { singer: '자우림', music: '팬이야', youtube_id: '-A5009Oi1qw' },
  { singer: '자우림', music: '일탈', youtube_id: 'es1-ui7O6vI' },
  { singer: '넬', music: '기억을 걷는 시간', youtube_id: 'VZnfZ14fIig' },
  { singer: '넬', music: '지구가 태양을 네 번', youtube_id: 'AJpPIu1gNms' },
  { singer: '넬', music: 'Stay', youtube_id: 'bmivgWKzGkM' },
  { singer: '넬', music: '마음을 잃다', youtube_id: 'ClMOcjpksco' },
  { singer: '넬', music: '멀어지다', youtube_id: 'R550p0igOWs' },
  { singer: '넬', music: 'Good night', youtube_id: 'y2OguFc9LUQ' },
  { singer: '브라운 아이즈', music: '벌써 일년', youtube_id: 'gdj6a0hv0Uk' },
  { singer: '브라운 아이즈', music: '가지마 가지마', youtube_id: 'aq4_0vH2728' },
  { singer: '브라운 아이드 소울', music: '정말 사랑했을까', youtube_id: 'NsRHHcTJYUs' },
  { singer: '브라운 아이드 소울', music: 'Nothing Better', youtube_id: 'bGZon5xAgpg' },
  { singer: '브라운 아이드 걸스', music: 'Abracadabra', youtube_id: 'I8ciDS40Ujk' },
  { singer: '브라운 아이드 걸스', music: 'LOVE', youtube_id: 'CdsQsniwoDk' },
  { singer: '브라운 아이드 걸스', music: '어쩌다', youtube_id: 'J3AjxAj_DpQ' },
  { singer: '브라운 아이드 걸스', music: 'Sixth Sense', youtube_id: 'vpZYR7HSYEw' },
  { singer: '부가킹즈', music: '틱택토', youtube_id: 'PGMRVqGagds' },
  { singer: '포맨', music: '못해', youtube_id: 'c_EjoWowAT4' },
  { singer: '포맨', music: '다시 사랑할 수 있을까', youtube_id: '8FfAtg0gaSs' },
  { singer: '백지영', music: '사랑안해', youtube_id: 'EAWHtXQpYX4' },
  { singer: '백지영', music: 'Dash', youtube_id: 'MI5ZIfD8n9s' },
  { singer: '백지영', music: '내 귀에 캔디', youtube_id: 'fE3wlJoBenc' },
  { singer: '백지영', music: '부담', youtube_id: 'G8Q_4UIqer4' },
  { singer: '백지영', music: 'Sad Salsa', youtube_id: 'niJkqSkdCjg' },
  { singer: 'Zion.T', music: 'No Make Up', youtube_id: 'HxgK6jgRjQw' },
  { singer: 'Zion.T', music: '꺼내 먹어요', youtube_id: 'Sp_Z2tBVniI' },
  { singer: 'Zion.T', music: '양화대교', youtube_id: 'yP459cBS4f0' },
  { singer: 'Zion.T', music: '노래', youtube_id: '7TJj78pi5ms' },
  { singer: 'Zion.T', music: '눈', youtube_id: 'sz7V77p1Jrw' },
  { singer: '조성모', music: 'To Heaven', youtube_id: 'U3fGhJhGgw4' },
  { singer: '조성모', music: '아시나요', youtube_id: '12W5qcG2vXw' },
  { singer: '조성모', music: '다짐', youtube_id: 'sH_BAhP3Ozc' },
  { singer: '싸이', music: '강남스타일', youtube_id: '4AgDYTuZWOw' },
  { singer: '싸이', music: 'GENTLEMAN', youtube_id: 'Y7n5JX0zxSw' },
  { singer: '싸이', music: 'New Face', youtube_id: 'yPFmf_bY1vw' },
  { singer: '싸이', music: '어땠을까', youtube_id: 'iT267zwmFBw' },
  { singer: '싸이', music: 'DADDY', youtube_id: 'rlQ0NdDsaw8' },
  { singer: '악동뮤지션', music: '어떻게 이별까지 사랑하겠어, 널 사랑하는 거지', youtube_id: 'KczYjTVrK_o' },
  { singer: '악동뮤지션', music: 'Give Love', youtube_id: '_bWN1LYQHvI' },
  { singer: '악동뮤지션', music: '오랜 날 오랜 밤', youtube_id: 'G7TqsFwWTM0' },
  { singer: '악동뮤지션', music: '200%', youtube_id: '5UrL0CM2uQA' },
  { singer: '악동뮤지션', music: '낙하', youtube_id: 'uaejCvCMu5I' },
  { singer: '악동뮤지션', music: 'DINOSAUR', youtube_id: 'zzfYBupjwIc' },
  { singer: '악동뮤지션', music: 'RE-BYE', youtube_id: '_KDzN-lxjlo' },
  { singer: '노을', music: '늦은 밤 너의 집 앞 골목길에서', youtube_id: 'r-vcN6-uBmk' },
  { singer: '노을', music: '너는 어땠을까', youtube_id: 'TmyMV2Nj42Q' },
  { singer: '노을', music: '그리워 그리워', youtube_id: 'j8mbW0jW-T0' },
  { singer: '노을', music: '청혼', youtube_id: 'jgbLdMmBIPU' },
  { singer: '볼빨간사춘기', music: '여행', youtube_id: 'DMcRIihAq9Q' },
  { singer: '볼빨간사춘기', music: '나만, 봄', youtube_id: 'bWPxFjZ2GX0' },
  { singer: '볼빨간사춘기', music: '우주를 줄게', youtube_id: '0i2wOl5PDOw' },
  { singer: '카라', music: '루팡 (Lupin)', youtube_id: 'R2TzZhpQc5M' },
  { singer: '카라', music: '미스터', youtube_id: '54J00GwB51s' },
  { singer: '카라', music: 'STEP', youtube_id: 'wcHbR--EkGA' },
  { singer: '카라', music: '점핑', youtube_id: 'eShlk9DVjYQ' },
  { singer: 'f(x)', music: 'Hot Summer', youtube_id: 'xTfbMYBoFik' },
  { singer: 'f(x)', music: 'Electric Shock', youtube_id: 'xWsA7CafvcQ' },
  { singer: 'f(x)', music: '첫 사랑니', youtube_id: 'hcMktKzONYs' },
  { singer: '임창정', music: '소주 한 잔', youtube_id: 'Q6ChonO-4iM' },
  { singer: '임창정', music: '내가 저지른 사랑', youtube_id: 'AcSJXKC2Bvk' },
  { singer: '임창정', music: '날 닮은 너', youtube_id: 'O2V1fCad2oU' },
  { singer: '(여자)아이들', music: 'LATATA', youtube_id: 'KGKhqdtUWyU' },
  { singer: '(여자)아이들', music: 'TOMBOY', youtube_id: 'aFoqCI75WoY' },
  { singer: '(여자)아이들', music: '화', youtube_id: 'DOjxbtafGYk' },
  { singer: '(여자)아이들', music: '덤디덤디', youtube_id: 'IZwze68yHuM' },
  { singer: '(여자)아이들', music: '한', youtube_id: 'IoNrByu93BA' },
  { singer: '2NE1', music: 'Lonely', youtube_id: 'vfRTbJNy87Q' },
  { singer: '2NE1', music: 'Fire', youtube_id: '48ZRVhNl1wA' },
  { singer: '박봄', music: 'You and I', youtube_id: 'dYHMGICzyPc' },
  { singer: '2NE1', music: 'I Don\'t Care', youtube_id: 'ORHR-ZA4RyM' },
  { singer: '가인', music: 'Bloom(피어나)', youtube_id: 'Qr3rcr7H2AQ' },
  { singer: '가인', music: 'Carnival (The Last Day)', youtube_id: 'wAuLtKPoaRs' },
  { singer: '포미닛', music: 'Hot Issue', youtube_id: 'B8p-zOux9s8' },
  { singer: '포미닛', music: '미쳐', youtube_id: 'OZOOMgOshEg' },
  { singer: '현아', music: 'Bubble Pop!', youtube_id: 'bX8t_fTzSLI' },
  { singer: '현아', music: '빨개요', youtube_id: 'LrJ4ATXneb0' },
  { singer: '현아', music: 'I’m Not Cool', youtube_id: 'YdIZtf7UUFA' },
  { singer: 'CNBLUE', music: '외톨이야', youtube_id: 'BRIGlW12qpk' },
  { singer: '틴탑', music: '장난아냐', youtube_id: '09wCMJ-PlMQ' },
  { singer: '틴탑', music: '향수 뿌리지마', youtube_id: 'PzfblneA574' },
  { singer: '인피니트', music: '내꺼하자', youtube_id: 'WvkX8e2pC0g' },
  { singer: '인피니트', music: 'BTD (Before The Dawn)', youtube_id: 'OIxiIRfzmS8' },
  { singer: '프리스타일', music: 'Y (Please Tell Me Why)', youtube_id: 'MKYv5w0QqFM' },
  { singer: '프리스타일', music: '수취인불명', youtube_id: 'bCJo43KxLz8' },
  { singer: '나얼', music: '바람기억', youtube_id: 'wyejTBPksy0' },
  { singer: '나얼', music: '같은 시간 속의 너', youtube_id: '2jza9S7ZMO0' },
  { singer: '나얼', music: '귀로', youtube_id: 'upA01bvUemQ' },
  { singer: '나얼', music: '기억의 빈자리', youtube_id: 'hEmsAYp-u3o' },
  { singer: '샵(S#arp)', music: 'Sweety', youtube_id: '4LsHTLr41o8' },
  { singer: '샵(S#arp)', music: '내 입술 따뜻한 커피처럼', youtube_id: 'dJ9DlCvL0a4' },
  { singer: '샵(S#arp)', music: 'Tell Me, Tell Me', youtube_id: '7V4NV4Douzo' },
  { singer: '샵(S#arp)', music: '가까이', youtube_id: 'n_28BGqfvE8' },
  { singer: '청하', music: '벌써 12시', youtube_id: 'od9UKd-yvks' },
  { singer: '청하', music: 'PLAY', youtube_id: 'bF9AOVAnVaU' },
  { singer: '청하', music: '롤러코스터', youtube_id: '8JXc4idKS_c' },
  { singer: '선미', music: '가시나', youtube_id: 'FV003QMWhNM' },
  { singer: '선미', music: '꼬리', youtube_id: '6_vDL6_aVm8' },
  { singer: '선미', music: '보라빛 밤', youtube_id: 'wh7j1uEpNsQ' },
  { singer: '테이', music: '사랑은...향기를 남기고', youtube_id: '4wuZsWr4kK4' },
  { singer: '테이', music: '그리움을 사랑한 가시나무', youtube_id: '5oU-SkWXa4A' },
  { singer: '나윤권', music: '기대', youtube_id: 'CzATSIwnTsM' },
  { singer: '나윤권', music: '나였으면', youtube_id: '6JQSnQiSgJ0' },
  { singer: '버즈', music: '가시', youtube_id: 'eq8_0g4YBPc' },
  { singer: '버즈', music: '남자를 몰라', youtube_id: 'rgms0zs6SZc' },
  { singer: '버즈', music: '겁쟁이', youtube_id: 'qkIrcN04AyQ' },
  { singer: '버즈', music: '나에게로 떠나는 여행', youtube_id: 'fqdgHKMqUp0' },
  { singer: '버즈', music: 'Monologue', youtube_id: 'yQ7X3mUl_F0' },
  { singer: '윤도현', music: '사랑했나봐', youtube_id: 'MDNzHG4DDhE' },
  { singer: '윤도현', music: '사랑 Two', youtube_id: '3Uf5dVnAhFg' },
  { singer: '하림', music: '사랑이 다른 사랑으로 잊혀지네', youtube_id: 'ZL7VL27ztyY' },
  { singer: '하림', music: '난치병', youtube_id: 'Z68m28YT4FQ' },
  { singer: '적재', music: '별 보러 가자', youtube_id: 'TlaGDYbxnJk' },
  { singer: '적재', music: '나랑 같이 걸을래', youtube_id: 'cn8gCkw6H5A' },
  { singer: '긱스', music: 'Officially missing you', youtube_id: 'dJRkhdWsu_M' },
  { singer: '다이나믹듀오', music: '고백', youtube_id: 'SruUnOJE_j0' },
  { singer: '다이나믹듀오', music: 'Ring My Bell', youtube_id: 'kEuc2w2HVhY' },
  { singer: '다이나믹듀오', music: '죽일놈', youtube_id: 'PJfZViVdOwM' },
  { singer: '빈지노', music: 'Aqua Man', youtube_id: '08h8u8Z9iJQ' },
  { singer: '슈프림팀', music: 'Dang Dang Dang', youtube_id: 'piyWxr0Em9Q' },
  { singer: '슈프림팀', music: 'Supermagic', youtube_id: 'zCOGV0KzQpQ' },
  { singer: '슈프림팀', music: '너 때문이야(feat. Soulman)', youtube_id: 'zmMiATGtHAU' },
  { singer: 'BMK', music: '꽃 피는 봄이 오면', youtube_id: 'Z7lTmPWvpaI' },
  { singer: 'SG워너비', music: 'Timeless', youtube_id: 'qqoHyTAFIPs' },
  { singer: 'SG워너비', music: '라라라', youtube_id: 'eAoTw0xBtM0' },
  { singer: 'SG워너비', music: '내사람', youtube_id: 'G5hbOrbfSRY' },
  { singer: '윤미래', music: '시간이 흐른뒤', youtube_id: 'zGgIzbahCZ0' },
  { singer: '창모', music: 'METEOR', youtube_id: '_50jtkDnObw' },
  { singer: '창모', music: '마에스트로 Maestro', youtube_id: 'YyMUqbK5RZ0' },
  { singer: '에코', music: '행복한 나를', youtube_id: 'Y_zpC4f5O6A' },
  { singer: '아웃사이더', music: '외톨이', youtube_id: 'HCslYhHcWkU' },
  { singer: '드렁큰 타이거', music: '난 널 원해', youtube_id: 'Qr3o9xMaIcc' },
  { singer: '드렁큰 타이거', music: 'Monster', youtube_id: 'Jvdy40LrV_0' },
  { singer: '드렁큰 타이거', music: '너희가 힙합을 아느냐?', youtube_id: 'RPZxPwiDoek' },
  { singer: '델리스파이스', music: '고백', youtube_id: 'BYyVDi8BpZw' },
  { singer: '휘성', music: '다시 만난 날', youtube_id: '1pQG5WXZjhg' },
  { singer: '휘성', music: 'With Me', youtube_id: 'O0z7yy2XGdU' },
  { singer: '휘성', music: '안되나요', youtube_id: 'fp_iwAFsB_I' },
  { singer: '휘성', music: '결혼까지 생각했어', youtube_id: '9xJy-KbTQX0' },
  { singer: '휘성', music: '가슴 시린 이야기', youtube_id: 'DduoqyK2CI0' },
  { singer: '플라워', music: 'Endless', youtube_id: 'xEIu-Hl4m-s' },
  { singer: '플라워', music: '애정표현', youtube_id: 'ltSNQxOZ1qo' },
  { singer: '조장혁', music: '중독된 사랑', youtube_id: 'Ap0Z4J5MmLA' },
  { singer: '포지션', music: 'I LOVE YOU', youtube_id: 'gqdQy6pyCy4' },
  { singer: '유미', music: '사랑은 언제나 목 마르다', youtube_id: '_SBWqC9cljU' },
  { singer: '터보', music: '회상', youtube_id: '0FXoS7DI-Ww' },
  { singer: '터보', music: '검은 고양이 네로', youtube_id: 'M9CnuQ8X5Pg' },
  { singer: '터보', music: 'Twist king', youtube_id: 'ZAIgqJee6Kc' },
  { singer: '이지', music: '응급실', youtube_id: 'E-BvyQb7mWE' },
  { singer: '거미', music: 'You Are My Everything', youtube_id: 'XvE8T99zpUw' },
  { singer: '거미', music: '친구라도 될 걸 그랬어', youtube_id: 'j6R70cI4bvs' },
  { singer: '거미', music: '날 그만 잊어요', youtube_id: 'Xc6IHbaxPlU' },
  { singer: '거미', music: '기억상실', youtube_id: 'em0lGANmAUU' },
  { singer: '거미', music: '어른아이', youtube_id: 'ISc10DFy43Y' },
  { singer: '빅마마', music: '체념', youtube_id: 'ULfAaYIuldI' },
  { singer: '빅마마', music: 'Break Away', youtube_id: 'tKv1E7ITA3c' },
  { singer: '빅마마', music: '배반', youtube_id: '6achxgklpv4' },
  { singer: '더넛츠', music: '사랑의 바보', youtube_id: 'gAz5CB9UXI8' },
  { singer: '더넛츠', music: '내 사람입니다', youtube_id: '77BE9NahcLc' },
  { singer: '씨야', music: '사랑의 인사', youtube_id: 'wRdNZKsh_a0' },
  { singer: '다비치', music: '두사랑', youtube_id: 'scRtFMzQQDs' },
  { singer: '다비치', music: '안녕이라고 말하지마', youtube_id: '90ie319tqIs' },
  { singer: '다비치', music: '8282', youtube_id: 'c54FzJcol3I' },
  { singer: '다비치', music: '그냥 안아달란 말야', youtube_id: 'xomiVINvVNE' },
  { singer: '손담비', music: '토요일밤에', youtube_id: '_FJu0rqYMR0' },
  { singer: '손담비', music: '미쳤어', youtube_id: '5maMAv48OcM' },
  { singer: '김동률', music: '다시 사랑한다 말할까', youtube_id: '1oGHSDyDEqA' },
  { singer: '김동률', music: '감사', youtube_id: 'oDlLNTwInBM' },
  { singer: '김동률', music: '답장', youtube_id: 'oLoeICdnBGM' },
  { singer: '김동률', music: '그게 나야', youtube_id: 'ZBSOlMRxil4' },
  { singer: '김동률', music: '취중진담', youtube_id: 'j1J3ZUd1Nqo' },
  { singer: '김동률', music: '출발', youtube_id: 'LTudX-OM7AI' },
  { singer: '김동률', music: 'REPLAY', youtube_id: 'aLOEVbNko9c' },
  { singer: '김동률', music: '오래된 노래', youtube_id: 'uuI7SsiRCuM' },
  { singer: '원타임', music: 'HOT 뜨거', youtube_id: 'lGHJtsYg1sA' },
  { singer: '원타임', music: 'Without You', youtube_id: 'T6cdoRHAHFY' },
  { singer: '혁오', music: 'TOMBOY', youtube_id: 'zC8RrOA0spo' },
  { singer: '혁오', music: '위잉위잉', youtube_id: 'bVrW1eDMtL8' },
  { singer: '피플크루', music: '너에게', youtube_id: 'nCvHqTW2sew' },
  { singer: '피플크루', music: '너에게 두번째 이야기', youtube_id: '1s1BNQiW69g' },
  { singer: '이적', music: '빨래', youtube_id: 'AYSTCqxAuTM' },
  { singer: '이적', music: '걱정말아요 그대', youtube_id: 'gPgxBHRA0lc' },
  { singer: '이적', music: '거짓말 거짓말 거짓말', youtube_id: 'bRvTUid-pBI' },
  { singer: '이적', music: '하늘을 달리다', youtube_id: 'Z4itGGZTrtQ' },
  { singer: '쥬얼리', music: '니가 참 좋아', youtube_id: 'gsXQPVwEO34' },
  { singer: '쥬얼리', music: 'Super Star', youtube_id: 'l9Ih9zqtWJY' },
  { singer: '쥬얼리', music: 'One More Time', youtube_id: 'Hue_6PAhEfU' },
  { singer: '쥬얼리', music: 'TONIGHT', youtube_id: 'pPcpwlDJWuc' },
  { singer: '쥬얼리', music: 'AGAIN', youtube_id: 'wF6BkuPaG34' },
  { singer: '에매랄드캐슬', music: '발걸음', youtube_id: 'ZKOwyeFgcAo' },
  { singer: '야다', music: '이미 슬픈 사랑', youtube_id: 'rZnw6xKmAmI' },
  { singer: '야다', music: '진혼', youtube_id: 'xw5Rb6mFG-w' },
  { singer: '야다', music: '슬픈다짐', youtube_id: 'l8evrAepicM' },
  { singer: '김현성', music: 'Heaven', youtube_id: 'MPfr7QXZ9L8' },
  { singer: '쿨', music: '애상', youtube_id: '3YSfRCtZ-AY' },
  { singer: '쿨', music: '아로하', youtube_id: 'Ddw83SZD6Go' },
  { singer: '쿨', music: '슬퍼지려 하기전에', youtube_id: 'JdeeJaHETfg' },
  { singer: '쿨', music: '운명', youtube_id: 'Wbjqdr1ILtw' },
  { singer: '쿨', music: '해변의 여인', youtube_id: 'x28aE-d2chY' },
  { singer: '쿨', music: 'All for You', youtube_id: 'EnNpExButdQ' },
  { singer: '박지윤', music: '성인식', youtube_id: 'KJcLkDgaC0A' },
  { singer: '박지윤', music: '난 사랑에 빠졌죠', youtube_id: '3S0lxCtRikM' },
  { singer: '박지윤', music: '환상', youtube_id: '3RN2Oer_5EY' },
  { singer: '어반자카파', music: '널 사랑하지 않아', youtube_id: 'fYsDi91T-SA' },
  { singer: '어반자카파', music: '그때의 나, 그때의 우리', youtube_id: 'OgiahIH6jfk' },
  { singer: '어반자카파', music: '그날에 우리', youtube_id: '3zMKobnybuw' },
  { singer: '스탠딩 에그', music: '오래된 노래', youtube_id: 'DGHBegYCcmQ' },
  { singer: 'Apink', music: 'Mr. Chu', youtube_id: 'J5D8hezP6u0' },
  { singer: 'Apink', music: 'NoNoNo', youtube_id: 'G7idV3W77X0' },
  { singer: 'Apink', music: '1도 없어', youtube_id: 'IefVBVqgqrc' },
  { singer: 'Apink', music: 'FIVE', youtube_id: 'xBGdw0CkUWg' },
  { singer: 'Apink', music: '몰라요', youtube_id: '2UuCeA9Vd_8' },
  { singer: '씨스타', music: 'SHAKE IT', youtube_id: '9GdR-LL4J5o' },
  { singer: '씨스타', music: 'Touch my body', youtube_id: '3XaREItLqGU' },
  { singer: '씨스타', music: '나혼자', youtube_id: 'kLka40yzGWQ' },
  { singer: '씨스타', music: 'Give it to me', youtube_id: 'Ss4NnmEAN3U' },
  { singer: '씨스타', music: 'Loving U', youtube_id: 'sED0T4hJ7gs' },
  { singer: '미쓰 에이', music: 'Bad Girl Good Girl', youtube_id: 'sdtspSYyQXs' },
  { singer: '미쓰 에이', music: 'Hush', youtube_id: 'llLocv-NaL0' },
  { singer: '미쓰 에이', music: 'Good-bye Baby', youtube_id: 'qLlwXalrYu8' },
  { singer: '미쓰 에이', music: '다른 남자 말고 너', youtube_id: 'tKEfUEIUpTc' },
  { singer: '미쓰 에이', music: '남자 없이 잘 살아', youtube_id: 'rD6yUyBXQsw' },
  { singer: '박정현', music: '꿈에', youtube_id: 'Xx5QIdvLAv8' },
  { singer: '박정현', music: '미아', youtube_id: 'csL0muPg8JI' },
  { singer: '비스트', music: '비가 오는 날엔', youtube_id: 'NY47mqz4yCg' },
  { singer: '비스트', music: 'SHOCK', youtube_id: 'YHAXAcWxi0I' },
  { singer: 'DEAN(딘)', music: 'instagram', youtube_id: 'lq3NLUN8DDc' },
  { singer: 'DEAN(딘)', music: 'D (Half Moon)', youtube_id: 'KltW7c7RUsI' },
  { singer: '이수영', music: '라라라', youtube_id: '1xrIqdRlW6c' },
  { singer: '이수영', music: '휠릴리', youtube_id: 'QN93xJlT2Nk' },
  { singer: '이수영', music: '덩그러니', youtube_id: 'Rgbz365TMe8' },
  { singer: '이수영', music: 'I Believe', youtube_id: '0SEqLd0CRo8' },
  { singer: '에일리', music: '첫눈처럼 너에게 가겠다', youtube_id: 'G5Lj9tsCK6A' },
  { singer: '에일리', music: '보여줄게', youtube_id: 'ScREt-bQzdA' },
  { singer: '정재욱', music: '가만히 눈을 감고', youtube_id: 'jSX4_wOPSaw' },
  { singer: '버스커버스커', music: '벚꽃 엔딩', youtube_id: 'KvthiAoGTfo' },
  { singer: '버스커버스커', music: '여수 밤바다', youtube_id: 'eO8w9xFArpE' },
  { singer: '버스커버스커', music: '처음엔 사랑이란게', youtube_id: '6V8fc3IeZ20' },
  { singer: 'PSY', music: 'That That', youtube_id: 'kjLUM7eNukg' },
  { singer: 'PSY', music: 'Celeb', youtube_id: 'AR0gejb2p4s' },
]

export const stuffList = [
  { value: '책상' },
  { value: '모니터' },
  { value: '공책' },
  { value: '볼펜' },
  { value: '연필' },
  { value: '필통' },
  { value: '두루마지 휴지' },
  { value: '곽티슈' },
  { value: '물티슈' },
  { value: '마우스' },
  { value: '데스크매트' },
  { value: '책' },
  { value: '요가매트' },
  { value: '폼롤러' },
  { value: '메트리스' },
  { value: '침대' },
  { value: '식탁' },
  { value: '의자' },
  { value: '책꽂이' },
  { value: '책장' },
  { value: '모니터' },
  { value: '칫솔' },
  { value: '치약' },
  { value: '리모콘' },
  { value: '파우치' },
  { value: '바디로션' },
  { value: '바디워시' },
  { value: '샴푸' },
  { value: '린스' },
  { value: '트리트먼트' },
  { value: '시계' },
  { value: '반지' },
  { value: '목걸이' },
  { value: '귀걸이' },
  { value: '목도리' },
  { value: '치마' },
  { value: '원피스' },
  { value: '셔츠' },
  { value: '아이쉐도우' },
  { value: '마스카라' },
  { value: '립밤' },
  { value: '립스틱' },
  { value: '바디스크럽' },
  { value: '비누' },
  { value: '손세정제' },
  { value: '마스크' },
  { value: '디퓨저' },
  { value: '캔들' },
  { value: '컵' },
  { value: '접시' },
  { value: '숟가락' },
  { value: '젓가락' },
  { value: '도마' },
  { value: '병따개' },
  { value: '시계' },
  { value: '액자' },
  { value: '소파' },
  { value: '서랍' },
  { value: '양말' },
  { value: '통기타' },
  { value: '일렉기타' },
  { value: '베이스' },
  { value: '드럼' },
  { value: '섹소폰' },
  { value: '피아노' },
  { value: '사원증' },
  { value: '명함' },
  { value: '운동화' },
  { value: '구두' },
  { value: '슬리퍼' },
  { value: '감자깍기칼' },
  { value: '국자' },
  { value: '바가지' },
  { value: '수세미' },
  { value: '걸레' },
  { value: '행주' },
  { value: '팔찌' },
  { value: '머리띠' },
  { value: '머리끈' },
  { value: '머리핀' },
  { value: '거울' },
  { value: '꽃병' },
  { value: '부채' },
  { value: '이불' },
  { value: '물통' },
  { value: '텐트' },
  { value: '제습제' },
  { value: '수건' },
  { value: '냄비' },
  { value: '후라이팬' },
  { value: '옷걸이' },
  { value: '스테이플러(호치케스)' },
  { value: '펀치' },
  { value: '다이어리' },
  { value: '고무장갑' },
  { value: '락스' },
  { value: '보온병' },
  { value: '젖병' },
  { value: '뒤집개' },
  { value: '버너' },
  { value: '냄비받침' },
  { value: '빨래건조대' },
  { value: '줄넘기' },
  { value: '아령' },
  { value: '쓰레기통' },
  { value: '먼지털이' },
  { value: '핸드크림' },
  { value: '수분크림' },
  { value: '비닐봉투' },
  { value: '탈취제' },
  { value: '가글' },
  { value: '가방' },
  { value: '장갑' },
  { value: '모자' },
]

export const emotionList = [
  { value: '기쁨' },
  { value: '분노' },
  { value: '슬픔' },
  { value: '즐거움' },
  { value: '사랑' },
  { value: '증오' },
  { value: '욕망' },
  { value: '감동' },
  { value: '그리움' },
  { value: '권태' },
  { value: '수치심' },
  { value: '실망' },
  { value: '애증' },
  { value: '억울' },
  { value: '원망' },
  { value: '박진감' },
  { value: '자괴감' },
  { value: '자신감' },
  { value: '죄책감' },
  { value: '질투' },
  { value: '집착' },
  { value: '짜증' },
  { value: '호기심' },
  { value: '불쾌' },
  { value: '상쾌' },
  { value: '행복' },
  { value: '불행' },
  { value: '희망' },
  { value: '절망' },
  { value: '두려움' },
  { value: '설렘' },
  { value: '걱정' },
  { value: '기대' },
  { value: '괘씸' },
  { value: '부끄러움' },
  { value: '혐오' },
  { value: '감사' },
  { value: '놀람' },
  { value: '뿌듯함' },
  { value: '짜릿함' },
  { value: '포근함' },
  { value: '흐뭇한' },
  { value: '흥분' },
  { value: '불만' },
  { value: '우울' },
  { value: '외로움' },
  { value: '뭉클' },
  { value: '창피' },
  { value: '울적함' },
  { value: '지루함' },
  { value: '신남' },
  { value: '다정' },
  { value: '끔찍' },
  { value: '부담' },
  { value: '궁금함' },
]

export const applianceList = [
  { value: '청소기' },
  { value: '로봇청소기' },
  { value: '카메라' },
  { value: '선풍기' },
  { value: '다리미' },
  { value: '칫솔살균기' },
  { value: '세탁기' },
  { value: '건조기' },
  { value: 'TV' },
  { value: '스피커' },
  { value: '태블릿 PC' },
  { value: '스마트워치' },
  { value: '노트북' },
  { value: '식기세척기' },
  { value: '라면포트' },
  { value: '멀티포트' },
  { value: '외장하드' },
  { value: '헤드셋' },
  { value: '이어폰' },
  { value: 'E-북 리더' },
  { value: '빔프로젝터' },
  { value: '플레이스테이션' },
  { value: '닌텐도' },
  { value: '냉장고' },
  { value: '커피머신' },
  { value: '인덕션' },
  { value: '에어컨' },
  { value: '전동칫솔' },
  { value: '비데' },
  { value: '체중계' },
  { value: 'CCTV' },
  { value: '안마의자' },
  { value: '발마사지기' },
  { value: '족욕기' },
  { value: '보풀제거기' },
  { value: '음식물냉장고' },
  { value: '음식물처리기' },
  { value: '드라이기' },
  { value: '전동면도기' },
  { value: '턴테이블' },
  { value: '엠프' },
  { value: '해충퇴치기' },
  { value: '온풍기' },
  { value: '온수매트' },
  { value: '전기장판' },
  { value: '공기청정기' },
  { value: '오븐' },
  { value: '전자레인지' },
  { value: '밥솥' },
  { value: '에어프라이어' },
  { value: '믹서기' },
  { value: '토스터' },
  { value: '정수기' },
  { value: '전기그릴' },
  { value: '약탕기' },
  { value: '전기포트' },
  { value: '고데기' },
]

export const classicList = [
  { value: '녹턴', composer: '쇼팽', youtube_id: 'zql8G-4gE7' },
  { value: '사랑의인사', composer: '엘가', youtube_id: 'HcU3IXoJvWg' },
  { value: '송어', composer: '슈베르트', youtube_id: '11t26dpCa_I' },
  { value: '엘리제를 위하여', composer: '베토벤', youtube_id: '_XG3h6LywNQ' },
  { value: '월광소나타', composer: '베토벤', youtube_id: '9_C6CTs0WhI' },
  { value: '즉흥환상곡', composer: '쇼팽', youtube_id: 'xzObtOqeSEc' },
  { value: '소녀의 기도', composer: '바다르체프스카', youtube_id: 'rxeEbO47QSw' },
  { value: '마왕', composer: '슈베르트', youtube_id: 'BDv3Lz2TfXc' },
  { value: '호두까기 인형 행진곡', composer: '차이코프스키', youtube_id: 'aeUrBUI-8qs' },
  { value: '벡조의 호수', composer: '차이코프스키', youtube_id: 'CS26BJ_ntwo' },
  { value: '터키행진곡', composer: '모차르트', youtube_id: 'A47y1r0o3NI' },
  { value: '사계 - 봄 3악장', composer: '비발디', youtube_id: 'KasDwDzqmq0' },
  { value: '사계 - 여름 3악장', composer: '비발디', youtube_id: '25UX6FjoIIw' },
  { value: '사계 - 가을 1악장', composer: '비발디', youtube_id: '6BMavsrdu_w' },
  { value: '사계 - 겨울 2악장', composer: '비발디', youtube_id: 'AXVzaizbcvY' },
  { value: 'G선상의 아리아', composer: '바흐', youtube_id: 'pyX-lxPkYbE' },
  { value: '아이네클라이네 나흐트뮤지크(세레나데 13번)', composer: '모차르트', youtube_id: 'UhPBT0dA_oA' },
  { value: '사랑의 기쁨', composer: '크라이슬러', youtube_id: 'LjC0zYUk7Cs' },
  { value: '사랑의 꿈', composer: '리스트', youtube_id: 'H3WrcsaL-FY' },
  { value: '투우사의 노래', composer: '비제', youtube_id: '0d9FtG1PeSs' },
  { value: '캉캉', composer: '오펜바흐', youtube_id: 'UQvet8SAf0c' },
  { value: '봄의 왈츠', composer: '요한스트라우스', youtube_id: 'YJ018K2xaBA' },
  { value: '신세계로부터', composer: '드보르작', youtube_id: 'mJjk7vbVaOY' },
  { value: '왈츠 2번', composer: '쇼스타코비치', youtube_id: 'gYSRrer6iO8' },
  { value: '헝가리무곡', composer: '브람스', youtube_id: 'HNmVe0Mmek' },
  { value: '지고이네르바이젠', composer: '사라사테', youtube_id: 'tQhpibnOWTw' },
  { value: '소나타 16번', composer: '모차르트', youtube_id: 'qjk-YRuQZDE' },
  { value: '사라방드', composer: '헨델', youtube_id: 'up1gDwjRVqs' },
  { value: '달빛', composer: '드뷔시', youtube_id: 'xl6qDlPCTUM' },
]

export const foodList = [
  { value: '김치찌개' },
  { value: '된장찌개' },
  { value: '생선구이' },
  { value: '등갈비찜' },
  { value: '갈비탕' },
  { value: '갈비찜' },
  { value: '김치볶음밥' },
  { value: '호박죽' },
  { value: '단호박스프' },
  { value: '파스타' },
  { value: '피자' },
  { value: '햄버거' },
  { value: '샐러드' },
  { value: '두부조림' },
  { value: '생선조림' },
  { value: '스시' },
  { value: '회' },
  { value: '짜장면' },
  { value: '짬뽕' },
  { value: '탕수육' },
  { value: '우육탕면' },
  { value: '추어탕' },
  { value: '장어탕' },
  { value: '감자탕' },
  { value: '뼈다귀해장국' },
  { value: '설렁탕' },
  { value: '곰탕' },
  { value: '만두' },
  { value: '수제비' },
  { value: '불고기' },
  { value: '잡채' },
  { value: '떡볶이' },
  { value: '비빔밥' },
  { value: '볶음밥' },
  { value: '간장게장' },
  { value: '청국장' },
  { value: '순두부' },
  { value: '삽겹살' },
  { value: '닭볶음탕' },
  { value: '제육볶음' },
  { value: '해물탕' },
  { value: '오므라이스' },
  { value: '계란말이' },
  { value: '육개장' },
  { value: '잔치국수' },
  { value: '막국수' },
  { value: '족발' },
  { value: '보쌈' },
  { value: '김밥' },
  { value: '라면' },
  { value: '우동' },
  { value: '돈가스' },
  { value: '낙지볶음' },
  { value: '팟타이' },
  { value: '카레' },
  { value: '마파두부' },
  { value: '류산슬' },
  { value: '깐풍기' },
  { value: '팔보채' },
  { value: '파전' },
  { value: '감자전' },
  { value: '소곱창구이' },
  { value: '야채곱창' },
  { value: '감바스 알 아히요' },
  { value: '빠에야' },
  { value: '포케' },
  { value: '토스트' },
  { value: '쌀국수' },
  { value: '똠양꿍' },
  { value: '치킨' },
  { value: '핫도그' },
  { value: '스테이크' },
]
