export const proverbList = [
  {
    value: '가는 날이 장날이다',
    masking: '가는 날이',
  },
  {
    value: '가는 말이 고와야 오는 말이 곱다',
    masking: '가는 말이 고와야',
  },
  {
    value: '가랑잎이 솔잎더러 바스락거린다고 한다',
    masking: '가랑잎이 솔잎더러',
  },
  {
    value: '가재는 게 편이다',
    masking: '가재는'
  },
  {
    value: '가지 많은 나무에 바람 잘 날 없다',
    masking: '가지 많은 나무에',
  },
  {
    value: '갈수록 태산',
    masking: '갈수록'
  },
  {
    value: '같은 값이면 다홍치마',
    masking: '같은 값이면',
  },
  {
    value: '개같이 벌어서 정승같이 쓴다',
    masking: '개같이 벌어서',
  },
  {
    value: '개구리 올챙이 적 생각을 못 한다',
    masking: '개구리',
  },
  {
    value: '개똥도 약에 쓰려면 없다',
    masking: '개똥도',
  },
  {
    value: '개밥에 도토리',
    masking: '개밥에',
  },
  {
    value: '개버릇 남 못 준다',
    masking: '개버릇',
  },
  {
    value: '개천에서 용 난다',
    masking: '개천에서',
  },
  {
    value: '계란에도 뼈가 있다',
    masking: '계란에도',
  },
  {
    value: '고기는 씹어야 맛이요, 말은 해야 맛이라',
    masking: '고기는 씹어야 맛이요,',
  },
  {
    value: '고기도 먹어 본 사람이 잘 먹는다',
    masking: '고기도 잘 먹는다',
  },
  {
    value: '고래 싸움에 새우 등 터진다',
    masking: '고래 싸움에',
  },
  {
    value: '고양이 목에 방울 달기',
    masking: '고양이 목에',
  },
  {
    value: '공든 탑이 무너지랴',
    masking: '공든 탑이',
  },
  {
    value: '구더기 무서워 장 못 담글까',
    masking: '구더기 무서워',
  },
  {
    value: '구르는 돌은 이끼가 끼지 않는다',
    masking: '구르는 돌은',
  },
  {
    value: '구슬이 서 말이라도 꿰어야 보배라',
    masking: '구슬이 서 말이라도',
  },
  {
    value: '굴러 온 돌이 박힌 돌 뺀다',
    masking: '굴러 온 돌이',
  },
  {
    value: '귀에 걸면 귀걸이, 코에 걸면 코걸이',
    masking: '귀에 걸면 귀걸이,',
  },
  {
    value: '그림의 떡',
    masking: '그림의',
  },
  {
    value: '금강산도 식후경',
    masking: '금강산도',
  },
  {
    value: '까마귀 날자 배 떨어진다',
    masking: '까마귀 날자',
  },
  {
    value: '꿩 대신 닭',
    masking: '꿩 대신',
  },
  {
    value: '꿩 먹고 알 먹기',
    masking: '꿩 먹고',
  },
  {
    value: '남의 잔치에 감 놓아라 배 놓아라 한다',
    masking: '남의 잔치에',
  },
  {
    value: '낫 놓고 기역 자 모른다',
    masking: '낫 놓고',
  },
  {
    value: '낮말은 새가 듣고 밤말은 쥐가 듣는다',
    masking: '낮말은 새가 듣고',
  },
  {
    value: '내 코가 석자',
    masking: '내 코가',
  },
  {
    value: '누워서 침 뱉기',
    masking: '누워서',
  },
  {
    value: '누워서 떡먹기',
    masking: '누워서',
  },
  {
    value: '늦게 배운 도둑질에 날 새는 줄 모른다',
    masking: '늦게 배운 도둑질에',
  },
  {
    value: '다 된 밥에 재 뿌리기',
    masking: '다 된 밥에',
  },
  {
    value: '달면 삼키고 쓰면 뱉는다',
    masking: '달면 삼키고',
  },
  {
    value: '닭 잡아 먹고 오리발 내민다',
    masking: '닭 잡아 먹고',
  },
  {
    value: '도둑이 제 발 저리다',
    masking: '도둑이',
  },
  {
    value: '돌다리도 두들겨 보고 건너라',
    masking: '돌다리도',
  },
  {
    value: '되로 주고 말로 받는다',
    masking: '되로 주고',
  },
  {
    value: '등잔 밑이 어둡다',
    masking: '등잔 밑이',
  },
  {
    value: '땅 짚고 헤엄치기',
    masking: '땅 짚고',
  },
  {
    value: '똥 묻은 개가 겨 묻은 개 나무란다',
    masking: '똥 묻은 개가',
  },
  {
    value: '뛰는 놈 위에 나는 놈 있다',
    masking: '뛰는 놈 위에',
  },
  {
    value: '마른 하늘에 날벼락',
    masking: '마른 하늘에',
  },
  {
    value: '마파람에 게눈 감추듯 한다',
    masking: '마파람에',
  },
  {
    value: '말 한마디에 천 냥 빚도 갚는다',
    masking: '말 한마디에',
  },
  {
    value: '매도 먼저 맞는 놈이 낫다',
    masking: '매도 먼저',
  },
  {
    value: '모로 가도 서울만 가면 된다',
    masking: '모로 가도',
  },
  {
    value: '목구멍이 포도청',
    masking: '목구멍이',
  },
  {
    value: '못 먹는 감 찔러나 본다',
    masking: '못 먹는 감',
  },
  {
    value: '미운 놈 떡 하나 더 준다',
    masking: '미운 놈',
  },
  {
    value: '믿는 도끼에 발등 찍힌다',
    masking: '믿는 도끼에',
  },
  {
    value: '밑 빠진 독에 물 붓기',
    masking: '밑 빠진 독에',
  },
  {
    value: '바늘 가는 데 실 간다',
    masking: '바늘 가는 데',
  },
  {
    value: '바늘 도둑이 소 도둑 된다',
    masking: '바늘 도둑이',
  },
  {
    value: '배보다 배꼽이 더 크다',
    masking: '배보다 배꼽이',
  },
  {
    value: '밥 먹을 때는 개도 안 건든다',
    masking: '밥 먹을 때는',
  },
  {
    value: '백지장도 맞들면 낫다',
    masking: '백지장도',
  },
  {
    value: '뱁새가 황새 따라간다',
    masking: '뱁새가 황새',
  },
  {
    value: '벼룩의 간 빼먹기',
    masking: '벼룩의',
  },
  {
    value: '병 주고 약 준다',
    masking: '병 주고',
  },
  {
    value: '보기 좋은 떡이 먹기도 좋다',
    masking: '보기 좋은 떡이',
  },
  {
    value: '불난 집에 부채질 한다',
    masking: '불난 집에',
  },
  {
    value: '비 온 뒤에 땅이 굳어진다',
    masking: '비 온 뒤에',
  },
  {
    value: '빈 수레가 요란하다',
    masking: '빈 수레가',
  },
  {
    value: '빛 좋은 개살구',
    masking: '빛 좋은',
  },
  {
    value: '사공이 많으면 배가 산으로 올라간다',
    masking: '사공이 많으면',
  },
  {
    value: '사촌이 땅을 사면 배가 아프다',
    masking: '사촌이 땅을 사면',
  },
  {
    value: '새발의 피',
    masking: '새발의'
  },
  {
    value: '서당 개 삼 년에 풍월을 읊는다',
    masking: '서당 개 삼 년에',
  },
  {
    value: '세 살 버릇 여든까지 간다',
    masking: '세 살 버릇',
  },
  {
    value: '소문난 잔치에 먹을 것 없다',
    masking: '소문난 잔치에',
  },
  {
    value: '소 잃고 외양간 고친다',
    masking: '소 잃고',
  },
  {
    value: '쇠뿔도 단김에 빼랬다',
    masking: '쇠뿔도',
  },
  {
    value: '수박 겉 핥기',
    masking: '수박',
  },
  {
    value: '십 년이면 강산도 변한다',
    masking: '십 년이면',
  },
  {
    value: '아는 길도 물어 가라',
    masking: '아는 길도',
  },
  {
    value: '아니 땐 굴뚝에 연기 나랴',
    masking: '아니 땐 굴뚝에',
  },
  {
    value: '아닌 밤중에 홍두깨',
    masking: '아닌 밤중에',
  },
  {
    value: '약방에 감초',
    masking: '약방에',
  },
  {
    value: '어물전 망신은 꼴뚜기가 시킨다',
    masking: '어물전 망신은',
  },
  {
    value: '엎드려 절 받기',
    masking: '엎드려',
  },
  {
    value: '여자 셋이 모이면 접시가 깨진다',
    masking: '여자 셋이 모이면',
  },
  {
    value: '열 길 물 속은 알아도 한 길 사람 속은 모른다',
    masking: '열 길 물 속은 알아도',
  },
  {
    value: '열 번 찍어 안 넘어가는 나무 없다',
    masking: '열 번 찍어',
  },
  {
    value: '오뉴월 감기는 개도 안 걸린다',
    masking: '오뉴월 감기는',
  },
  {
    value: '오르지 못할 나무는 쳐다보지도 말아라',
    masking: '오르지 못할 나무는',
  },
  {
    value: '우물에 가서 숭늉 찾는다',
    masking: '우물에 가서'
  },
  {
    value: '울며 겨자 먹기',
    masking: '울며',
  },
  {
    value: '웃는 낯에 침 뱉으랴',
    masking: '웃는 낯에',
  },
  {
    value: '원수는 외나무 다리에서 만난다',
    masking: '원수는',
  },
  {
    value: '원숭이도 나무에서 떨어진다',
    masking: '원숭이도',
  },
  {
    value: '윗물이 맑아야 아랫물도 맑다',
    masking: '윗물이 맑아야',
  },
  {
    value: '자라 보고 놀란 가슴 솥뚜껑 보고 놀란다',
    masking: '자라 보고 놀란 가슴',
  },
  {
    value: '잘 자랄 나무는 떡잎부터 알아본다',
    masking: '잘 자랄 나무는',
  },
  {
    value: '작은 고추가 더 맵다',
    masking: '작은 고추가',
  },
  {
    value: '점잖은 고양이가 부뚜막에 먼저 올라간다',
    masking: '점잖은 고양이가',
  },
  {
    value: '종로에서 뺨 맞고 한강 가서 눈 흘긴다',
    masking: '종로에서 뺨 맞고',
  },
  {
    value: '좋은 약은 입에 쓰다',
    masking: '좋은 약은',
  },
  {
    value: '쥐구멍에도 볕 들 날이 있다',
    masking: '쥐구멍에도',
  },
  {
    value: '지렁이도 밟으면 꿈틀한다',
    masking: '지렁이도 밟으면'
  },
  {
    value: '천 리 길도 한 걸음부터',
    masking: '천 리 길도',
  },
  {
    value: '칼로 물 베기',
    masking: '칼로'
  },
  {
    value: '콩 심은 데 콩 나고 팥 심은 데 팥 난다',
    masking: '콩 심은 데 콩 나고',
  },
  {
    value: '티끌 모아 태산',
    masking: '티끌 모아',
  },
  {
    value: '하늘의 별 따기',
    masking: '하늘의'
  },
  {
    value: '하늘이 무너져도 솟아날 구멍은 있다',
    masking: '하늘이 무너져도',
  },
  {
    value: '하룻강아지 범 무서운 줄 모른다',
    masking: '하룻강아지',
  },
  {
    value: '한 귀로 듣고 한 귀로 흘린다',
    masking: '한 귀로 듣고'
  },
  {
    value: '한 술 밥에 배 부르랴',
    masking: '한 술 밥에',
  },
  {
    value: '호랑이 굴에 들어가야 호랑이 새끼를 잡는다',
    masking: '호랑이 굴에 들어가야',
  },
  {
    value: '호랑이에게 물려가도 정신만 바짝 차리면 산다',
    masking: '호랑이에게 물려가도',
  },
  {
    value: '호랑이도 제 말 하면 온다',
    masking: '호랑이도',
  },
]

export const idiomList = [
  { value: '가렴주구' },
  { value: '가인박명' },
  { value: '각골난망' },
  { value: '각자도생' },
  { value: '감언이설' },
  { value: '감탄고토' },
  { value: '개과천선' },
  { value: '거두절미' },
  { value: '건곤일척' },
  { value: '견물생심' },
  { value: '결자해지' },
  { value: '결초보은' },
  { value: '경거망동' },
  { value: '경국지색' },
  { value: '고진감래' },
  { value: '공명정대' },
  { value: '과유불급' },
  { value: '괄목상대' },
  { value: '군계일학' },
  { value: '권선징악' },
  { value: '근묵자흑' },
  { value: '금상첨화' },
  { value: '금의환향' },
  { value: '금지옥엽' },
  { value: '기고만장' },
  { value: '기사회생' },
  { value: '기상천외' },
  { value: '난형난제' },
  { value: '내우외환' },
  { value: '노심초사' },
  { value: '다다익선' },
  { value: '단도직입' },
  { value: '대기만성' },
  { value: '대동소이' },
  { value: '동문서답' },
  { value: '독불장군' },
  { value: '동병상련' },
  { value: '동상이몽' },
  { value: '두문불출' },
  { value: '등하불명' },
  { value: '마이동풍' },
  { value: '막상막하' },
  { value: '문전성시' },
  { value: '배은망덕' },
  { value: '백골난망' },
  { value: '백년해로' },
  { value: '백년서생' },
  { value: '백발백중' },
  { value: '백전노장' },
  { value: '백척간두' },
  { value: '부전자전' },
  { value: '부창부수' },
  { value: '분골쇠신' },
  { value: '불로소득' },
  { value: '사면초가' },
  { value: '사필귀정' },
  { value: '산전수전' },
  { value: '살신성인' },
  { value: '삼고초려' },
  { value: '상전벽해' },
  { value: '새옹지마' },
  { value: '선견지명' },
  { value: '설상가상' },
  { value: '소원성취' },
  { value: '속수무책' },
  { value: '송구영신' },
  { value: '수수방관' },
  { value: '순망치한' },
  { value: '신출귀몰' },
  { value: '아비귀환' },
  { value: '안빈낙도' },
  { value: '약육강식' },
  { value: '어부지리' },
  { value: '어불성설' },
  { value: '언중유골' },
  { value: '역지사지' },
  { value: '오리무중' },
  { value: '오비이락' },
  { value: '오합지졸' },
  { value: '와신상담' },
  { value: '외유내강' },
  { value: '용두사미' },
  { value: '우이독경' },
  { value: '우후죽순' },
  { value: '유구무언' },
  { value: '유명무실' },
  { value: '유유상종' },
  { value: '이심전심' },
  { value: '인사불성' },
  { value: '인산인해' },
  { value: '일거양득' },
  { value: '일망타진' },
  { value: '일사천리' },
  { value: '일석이조' },
  { value: '일장춘몽' },
  { value: '일취월장' },
  { value: '일편단심' },
  { value: '임기응변' },
  { value: '자가당착' },
  { value: '자수성가' },
  { value: '자업자득' },
  { value: '자초지종' },
  { value: '작심삼일' },
  { value: '적반하장' },
  { value: '전광석화' },
  { value: '전화위복' },
  { value: '조강지처' },
  { value: '조삼모사' },
  { value: '좌불안석' },
  { value: '죽마고우' },
  { value: '중구난방' },
  { value: '천고마비' },
  { value: '천재일우' },
  { value: '천진난만' },
  { value: '천하태평' },
  { value: '철두철미' },
  { value: '출가외인' },
  { value: '침소봉대' },
  { value: '타산지석' },
  { value: '파죽지세' },
  { value: '패가망신' },
  { value: '표리부동' },
  { value: '학수고대' },
  { value: '함흥차사' },
  { value: '호사다마' },
  { value: '호시탐탐' },
  { value: '화룡점정' },
  { value: '환골탈태' },
  { value: '회자정리' },
  { value: '횡설수설' },
]

export const fourLetterVocabList = [
  { value: '강강술래' },
  { value: '계란말이' },
  { value: '계좌번호' },
  { value: '고속도로' },
  { value: '고속버스' },
  { value: '고슴도치' },
  { value: '그린벨트' },
  { value: '네덜란드' },
  { value: '뉴발란스' },
  { value: '다이어트' },
  { value: '데리야끼' },
  { value: '동그랑땡' },
  { value: '된장찌개' },
  { value: '두루치기' },
  { value: '드래곤볼' },
  { value: '라이선스' },
  { value: '마요네즈' },
  { value: '뭉게구름' },
  { value: '밀폐용기' },
  { value: '바이올린' },
  { value: '브라우니' },
  { value: '브라우저' },
  { value: '블랙핑크' },
  { value: '비밀번호' },
  { value: '비트박스' },
  { value: '비트코인' },
  { value: '비티에스' },
  { value: '선글라스' },
  { value: '샌드박스' },
  { value: '샌드위치' },
  { value: '스마트폰' },
  { value: '스파게티' },
  { value: '스타벅스' },
  { value: '스타워즈' },
  { value: '스타필드' },
  { value: '아이언맨' },
  { value: '아프리카' },
  { value: '안전운전' },
  { value: '알레르기' },
  { value: '업데이트' },
  { value: '오토바이' },
  { value: '오토바이' },
  { value: '올리브영' },
  { value: '요구르트' },
  { value: '우루과이' },
  { value: '우리나라' },
  { value: '우리은행' },
  { value: '유통기한' },
  { value: '이구아나' },
  { value: '종이접기' },
  { value: '총각김치' },
  { value: '카놀라유' },
  { value: '카카오톡' },
  { value: '코스모스' },
  { value: '코스프레' },
  { value: '크레파스' },
  { value: '퀵서비스' },
  { value: '타임머신' },
  { value: '타임캡술' },
  { value: '파인애플' },
  { value: '포도씨유' },
  { value: '포스트잍' },
  { value: '프로그램' },
  { value: '프리미엄' },
  { value: '페브리즈' },
  { value: '프라이팬' },
  { value: '플라스크' },
  { value: '피라미드' },
  { value: '해바라기' },
  { value: '헬리콥터' },
  { value: '휴대전화' },
]

export const photoList = [
  { name: '윤아', url: '', },
  { name: '김태리', url: '' },
  { name: '남주혁', url: '' },
  { name: '이보영', url: '' },
  { name: '지성', url: '' },
  { name: '박지성', url: '' },
  { name: '김태희', url: '' },
  { name: '한채영', url: '' },
  { name: '손흥민', url: '' },
  { name: '정우성', url: '' },
  { name: '이정재', url: '' },
  { name: '조이현', url: '' },
  { name: '이준기', url: '' },
  { name: '박지성', url: '' },
  { name: '이동국', url: '' },
  { name: '안정환', url: '' },
  { name: '이정현', url: '' },
  { name: '김성주', url: '' },
  { name: '김용만', url: '' },
  { name: '유재석', url: '' },
  { name: '지석진', url: '' },
  { name: '정준하', url: '' },
  { name: '박명수', url: '' },
  { name: '전소민', url: '' },
  { name: '하하', url: '' },
  { name: '이광수', url: '' },
  { name: '양세찬', url: '' },
  { name: '양세형', url: '' },
  { name: '김종국', url: '' },
  { name: '송지효', url: '' },
  { name: '강호동', url: '' },
  { name: '피오', url: '' },
  { name: '이수근', url: '' },
  { name: '은지원', url: '' },
  { name: '나영석', url: '' },
  { name: '송민호', url: '' },
  { name: '슈카', url: '' },
  { name: '안재현', url: '' },
  { name: '김창완', url: '' },
  { name: '공유', url: '' },
  { name: '채연', url: '' },
  { name: '윤은혜', url: '' },
  { name: '아이유', url: '' },
  { name: '야옹이작가', url: '' },
  { name: '손예진', url: '' },
  { name: '장동민', url: '' },
  { name: '유세윤', url: '' },
  { name: '문세윤', url: '' },
  { name: '유상무', url: '' },
  { name: '이용진', url: '' },
  { name: '이진호', url: '' },
  { name: '뱃사공', url: '' },
  { name: '정호연', url: '' },
  { name: '김사랑', url: '' },
  { name: '백예린', url: '' },
  { name: '츄', url: '' },
  { name: '유리', url: '' },
  { name: '이효리', url: '' },
  { name: '이효리', url: '' },
  { name: '성유리', url: '' },
  { name: '유진', url: '' },
  { name: '성시경', url: '' },
  { name: '장기하', url: '' },
  { name: '조세호', url: '' },
  { name: '장원영', url: '' },
  { name: '미주', url: '' },
  { name: '입짧은햇님', url: '' },
  { name: '김지원', url: '' },
  { name: '혜리', url: '' },
  { name: '박서준', url: '' },
  { name: '최우식', url: '' },
  { name: '김다미', url: '' },
  { name: '안재홍', url: '' },
  { name: '이병헌', url: '' },
  { name: '이민정', url: '' },
  { name: '현빈', url: '' },
  { name: '송혜교', url: '' },
  { name: '조승우', url: '' },
  { name: '조정석', url: '' },
  { name: '유연석', url: '' },
  { name: '전미도', url: '' },
  { name: '사나', url: '' },
  { name: '조나단', url: '' },
  { name: '조이', url: '' },
  { name: '박나래', url: '' },
  { name: '장도연', url: '' },
  { name: '베네딕트 컴버배치', url: '' },
  { name: '안젤리나 졸리', url: '' },
  { name: '임창정', url: '' },
  { name: '비욘세', url: '' },
  { name: '탐 크루즈', url: '' },
  { name: '이순재', url: '' },
  { name: '나문희', url: '' },
  { name: '윤여정', url: '' },
  { name: '박민영', url: '' },
  { name: '송강', url: '' },
  { name: '이성경', url: '' },
  { name: '구자철', url: '' },
  { name: '리오넬 메시', url: '' },
  { name: '윌 스미스', url: '' },
  { name: '모건 프리먼', url: '' },
  { name: '아만다 사이프리드', url: '' },
  { name: '한지민', url: '' },
  { name: '김혜자', url: '' },
  { name: '신구', url: '' },
  { name: '에릭', url: '' },
  { name: '정유미', url: '' },
  { name: '앤 헤서워이', url: '' },
  { name: '류승룡', url: '' },
  { name: '이하늬', url: '' },
  { name: '공명', url: '' },
  { name: '양조위', url: '' },
  { name: '천우희', url: '' },
  { name: '영심이', url: '' },
  { name: '하늬', url: '' },
  { name: '피카츄', url: '' },
  { name: '배두나', url: '' },
  { name: '김혜수', url: '' },
  { name: '이제훈', url: '' },
  { name: '조진웅', url: '' },
  { name: '크러쉬', url: '' },
  { name: '송은이', url: '' },
  { name: '김숙', url: '' },
  { name: '지드래곤', url: '' },
  { name: '소연', url: '' },
  { name: '박재범', url: '' },
  { name: '태연', url: '' },
  { name: '임영웅', url: '' },
  { name: '승희', url: '' },
  { name: '보아', url: '' },
  { name: '카리나', url: '' },
  { name: '윈터', url: '' },
  { name: '빌리 아일리쉬', url: '' },
  { name: '제시', url: '' },
  { name: '지코', url: '' },
  { name: '전현무', url: '' },
  { name: '노주현', url: '' },
  { name: '박영규', url: '' },
  { name: '올라프', url: '' },
  { name: '보노보노', url: '' },
  { name: '짱구', url: '' },
  { name: '도라에몽', url: '' },
  { name: '뽀로로', url: '' },
  { name: '둘리', url: '' },
  { name: '또치', url: '' },
  { name: '고길동', url: '' },
  { name: '희동이', url: '' },
  { name: '신데렐라', url: '' },
  { name: '앨리스', url: '' },
  { name: '푸우', url: '' },
  { name: '심슨', url: '' },
  { name: '엘사', url: '' },
  { name: '안나', url: '' },
  { name: '뷔', url: '' },
  { name: '이영자', url: '' },
  { name: '최화정', url: '' },
  { name: '최여진', url: '' },
  { name: '이현', url: '' },
  { name: '마시마로', url: '' },
  { name: '키티', url: '' },
  { name: '미키마우스', url: '' },
  { name: '주먹왕 랄프', url: '' },
  { name: '캐스퍼', url: '' },
  { name: '휴잭맨', url: '' },
  { name: '탕웨이', url: '' },
  { name: '박찬욱', url: '' },
  { name: '봉준호', url: '' },
  { name: '송강호', url: '' },
  { name: '틸다 스윈튼', url: '' },
  { name: '박해일', url: '' },
  { name: '고아성', url: '' },
  { name: '오달수', url: '' },
  { name: '김명민', url: '' },
  { name: '신하균', url: '' },
  { name: '김희선', url: '' },
  { name: '차태현', url: '' },
  { name: '하정우', url: '' },
  { name: '주지훈', url: '' },
  { name: '마동석', url: '' },
  { name: '찬열', url: '' },
  { name: '카이', url: '' },
  { name: '백지영', url: '' },
  { name: '성동일', url: '' },
  { name: '정은지', url: '' },
  { name: '엠마왓슨', url: '' },
  { name: '최민식', url: '' },
  { name: '곽도원', url: '' },
  { name: '안성기', url: '' },
  { name: '고아라', url: '' },
  { name: '박소담', url: '' },
  { name: '이솜', url: '' },
  { name: '유노윤호', url: '' },
  { name: '규현', url: '' },
  { name: '태민', url: '' },
  { name: '신동', url: '' },
  { name: '화사', url: '' },
  { name: '한혜진', url: '' },
  { name: '강다니엘', url: '' },
  { name: '노홍철', url: '' },
  { name: '개리', url: '' },
  { name: '길', url: '' },
  { name: '황정민', url: '' },
  { name: '신봉선', url: '' },
  { name: '레오나르도 다빈치', url: '' },
  { name: '케이트 윈슬렛', url: '' },
  { name: '라이언 레이노즈', url: '' },
  { name: '조셉 고든 레빗', url: '' },
  { name: '레이첼 맥아담스', url: '' },
  { name: '이민호', url: '' },
  { name: '구혜선', url: '' },
  { name: '임시완', url: '' },
  { name: '강소라', url: '' },
  { name: '이성민', url: '' },
  { name: '마크 러펄로', url: '' },
  { name: '유아인', url: '' },
  { name: '김고은', url: '' },
  { name: '이동욱', url: '' },
  { name: '김세정', url: '' },
  { name: '한가인', url: '' },
  { name: '딘딘', url: '' },
  { name: '류준열', url: '' },
  { name: '김윤아', url: '' },
  { name: '라미란', url: '' },
  { name: '박보검', url: '' },
  { name: '고경표', url: '' },
  { name: '차승원', url: '' },
  { name: '손호준', url: '' },
  { name: '유해진', url: '' },
  { name: '배정남', url: '' },
  { name: '이선균', url: '' },
  { name: '고두심', url: '' },
  { name: '이지아', url: '' },
  { name: '장기용', url: '' },
  { name: '임수정', url: '' },
  { name: '소피 마르소', url: '' },
  { name: '오드리 햅번', url: '' },
  { name: '케이윌', url: '' },
  { name: '박효신', url: '' },
  { name: '문재인', url: '' },
  { name: '윤석열', url: '' },
  { name: '도널드 트럼프', url: '' },
  { name: '권정열', url: '' },
  { name: '김용명', url: '' },
  { name: '헤이즈', url: '' },
  { name: '비', url: '' },
  { name: '김태희', url: '' },
  { name: '김종민', url: '' },
  { name: '줄리아 로버츠', url: '' },
  { name: '휴 그랜트', url: '' },
  { name: '키이라 나이틀리', url: '' },
  { name: '차은우', url: '' },
  { name: '한소희', url: '' },
  { name: '구교환', url: '' },
  { name: '전지현', url: '' },
  { name: '고든램지', url: '' },
  { name: '박보영', url: '' },
  { name: '정해인', url: '' },
  { name: '안영미', url: '' },
  { name: '한효주', url: '' },
  { name: '박정민', url: '' },
  { name: '공효진', url: '' },
  { name: '강하늘', url: '' },
  { name: '김지석', url: '' },
  { name: '이다희', url: '' },
  { name: '김영철', url: '' },
  { name: '민경훈', url: '' },
  { name: '서장훈', url: '' },
  { name: '이상민', url: '' },
  { name: '오은영', url: '' },
  { name: '이승기', url: '' },
  { name: '김무열', url: '' },
  { name: '윤승아', url: '' },
  { name: '정경호', url: '' },
  { name: '박미선', url: '' },
  { name: '이정은', url: '' },
  { name: '이시영', url: '' },
  { name: '강혜정', url: '' },
  { name: '타블로', url: '' },
  { name: 'KCM', url: '' },
  { name: '원슈타인', url: '' },
  { name: '노제', url: '' },
  { name: '가비', url: '' },
  { name: '셀레나 고메즈', url: '' },
  { name: '저스틴 비버', url: '' },
  { name: '아리아나 그란데', url: '' },
  { name: '이찬혁', url: '' },
  { name: '이수현', url: '' },
  { name: '홍현희', url: '' },
  { name: '제이슨', url: '' },
  { name: '김남길', url: '' },
  { name: '엄정화', url: '' },
  { name: '정형돈', url: '' },
  { name: '정형돈', url: '' },
  { name: '로꼬', url: '' },
  { name: '코드쿤스트', url: '' },
  { name: '미노이', url: '' },
  { name: '장윤정', url: '' },
  { name: '김남길', url: '' },
  { name: '장윤주', url: '' },
  { name: '한해', url: '' },
  { name: '넉살', url: '' },
  { name: '이종혁', url: '' },
  { name: '송일국', url: '' },
  { name: '박대기기자', url: '' },
  { name: '양준혁', url: '' },
  { name: '현주엽', url: '' },
  { name: '이덕화', url: '' },
  { name: '이형택', url: '' },
  { name: '박세리', url: '' },
  { name: '모태범', url: '' },
  { name: '김연아', url: '' },
  { name: '박태환', url: '' },
  { name: '김요한', url: '' },
  { name: '김동현', url: '' },
  { name: '김은정', url: '' },
  { name: '유시민', url: '' },
  { name: '유희열', url: '' },
  { name: '이적', url: '' },
  { name: '주현영', url: '' },
  { name: '김민교', url: '' },
  { name: '정상훈', url: '' },
  { name: '강유미', url: '' },
  { name: '죠지', url: '' },
  { name: '변요한', url: '' },
  { name: '설경구', url: '' },
  { name: '양동근', url: '' },
  { name: '조인성', url: '' },
  { name: '이영애', url: '' },
  { name: '하비에르 바르뎀', url: '' },
  { name: '히스 레저', url: '' },
  { name: '권오중', url: '' },
  { name: '김래원', url: '' },
  { name: '진구', url: '' },
  { name: '탁재훈', url: '' },
  { name: '김수미', url: '' },
  { name: '이호철', url: '' },
  { name: '이경영', url: '' },
  { name: '류승범', url: '' },
  { name: '염정아', url: '' },
  { name: '윤세아', url: '' },
  { name: '김우빈', url: '' },
  { name: '이수혁', url: '' },
  { name: '서인국', url: '' },
  { name: '최지우', url: '' },
  { name: '권상우', url: '' },
  { name: '장근석', url: '' },
  { name: '유승호', url: '' },
  { name: '유이', url: '' },
  { name: '박신혜', url: '' },
  { name: '이종석', url: '' },
  { name: '김영광', url: '' },
  { name: '전도연', url: '' },
  { name: '김주혁', url: '' },
  { name: '진서연', url: '' },
  { name: '한석규', url: '' },
  { name: '박신양', url: '' },
  { name: '김정은', url: '' },
  { name: '김정은', url: '' },
  { name: '박근혜', url: '' },
  { name: '이명박', url: '' },
  { name: '버락 오바마', url: '' },
  { name: '조지 부시', url: '' },
  { name: '푸틴', url: '' },
  { name: '마윈', url: '' },
  { name: '워렌버핏', url: '' },
  { name: '존리', url: '' },
  { name: '빌게이츠', url: '' },
  { name: '스티브잡스', url: '' },
  { name: '세종대왕', url: '' },
  { name: '이순신장군', url: '' },
  { name: '김영철', url: '' },
  { name: '유관순', url: '' },
  { name: '김구', url: '' },
  { name: '윤봉길', url: '' },
  { name: '안중근', url: '' },
  { name: '아인슈타인', url: '' },
  { name: '베토벤', url: '' },
  { name: '바흐', url: '' },
  { name: '빈센트 반 고흐', url: '' },
  { name: '모나리자', url: '' },
  { name: '에단 호크', url: '' },
  { name: '쿠사마 야요이', url: '' },
  { name: '엔디워홀', url: '' },
  { name: '살바도르 다리', url: '' },
  { name: '프리다칼로', url: '' },
  { name: '간디', url: '' },
  { name: '마틴 루터 킹', url: '' },
  { name: '체 게바라', url: '' },
  { name: '레오나르도 디카프리오', url: '' },
  { name: '클레오 파트라', url: '' },
  { name: '마돈나', url: '' },
  { name: '마이클잭슨', url: '' },
  { name: '프레디 머큐리', url: '' },
  { name: '마릴린먼로', url: '' },
  { name: '신사임당', url: '' },
  { name: '정주영', url: '' },
  { name: '민경훈', url: '' },
  { name: '김희철', url: '' },
  { name: '오드리햅번', url: '' },
  { name: '나훈이', url: '' },
  { name: '태진아', url: '' },
  { name: '설운도', url: '' },
  { name: '김구라', url: '' },
  { name: '윤종신', url: '' },
  { name: '김국진', url: '' },
  { name: '주호민', url: '' },
  { name: '이말년', url: '' },
  { name: '법정스님', url: '' },
  { name: '김수환추기경', url: '' },
  { name: '이건희', url: '' },
  { name: '이재용', url: '' },
  { name: '홍석천', url: '' },
  { name: '김민경', url: '' },
  { name: '준호', url: '' },
  { name: '제니', url: '' },
  { name: '한선화', url: '' },
  { name: '박인환', url: '' },
  { name: '장사익', url: '' },
  { name: '김덕수', url: '' },
  { name: '엄홍길', url: '' },
  { name: '가인', url: '' },
  { name: '별', url: '' },
  { name: '선우용녀', url: '' },
  { name: '김부자', url: '' },
  { name: '양희은', url: '' },
  { name: '천호진', url: '' },
  { name: '김혜숙', url: '' },
  { name: '김갑수', url: '' },
  { name: '서현진', url: '' },
  { name: '이서진', url: '' },
  { name: '마이클조던', url: '' },
  { name: '르브론제임스', url: '' },
  { name: '타이거우즈', url: '' },
  { name: '옹박', url: '' },
  { name: '주성치', url: '' },
  { name: '김수현', url: '' },
  { name: '박지선교수님', url: '' },
  { name: '이수정교수님', url: '' },
  { name: '권일용 프로파일러', url: '' },
  { name: '표창원 프로파일러', url: '' },
  { name: '이수정교수님', url: '' },
  { name: '김태호', url: '' },
  { name: '씨엘', url: '' },
  { name: '크리스탈', url: '' },
  { name: '김두영', url: '' },
  { name: '신세경', url: '' },
  { name: '리정', url: '' },
  { name: '혁오', url: '' },
  { name: '한효주', url: '' },
  { name: '이진욱', url: '' },
  { name: '이경규', url: '' },
  { name: '최불암', url: '' },
  { name: '조니뎁', url: '' },
  { name: '김유정', url: '' },
  { name: '기네스 팰트로', url: '' },
  { name: '두아리파', url: '' },
  { name: '선미', url: '' },
  { name: '현아', url: '' },
  { name: '최시원', url: '' },
  { name: '호날두', url: '' },
  { name: '베컴', url: '' },
]

export const animalList = [
  { value: '고양이' },
  { value: '개(강아지)' },
  { value: '개미' },
  { value: '게' },
  { value: '개구리' },
  { value: '고슴도치' },
  { value: '거북이' },
  { value: '고래' },
  { value: '기린' },
  { value: '나비' },
  { value: '나무늘보' },
  { value: '너구리' },
  { value: '늑대' },
  { value: '다람쥐' },
  { value: '닭' },
  { value: '도마뱀' },
  { value: '돼지' },
  { value: '말' },
  { value: '박쥐' },
  { value: '비둘기' },
  { value: '모기' },
  { value: '미어켓' },
  { value: '바퀴벌레' },
  { value: '병아리' },
  { value: '사자' },
  { value: '상어' },
  { value: '소' },
  { value: '새우' },
  { value: '수달' },
  { value: '스컹크' },
  { value: '악어' },
  { value: '앵무새' },
  { value: '양' },
  { value: '여우' },
  { value: '오리' },
  { value: '조개' },
  { value: '캥거루' },
  { value: '타조' },
  { value: '토끼' },
  { value: '파리' },
  { value: '팬더' },
  { value: '하이에나' },
  { value: '햄스터' },
  { value: '호랑이' },
]

export const movieList = [
  { value: '' }
]

export const singerList = [
  { value: '' }
]

export const musicList = [
  { value: '' }
]

export const stuffList = [
  { value: '' }
]

export const emotionList = [
  { value: '' }
]

export const celebrityList = [
  { value: '' }
]

export const applianceList = [
  { value: '' }
]

export const scriptList = [
  { value: '' }
]

export const classicList = [
  { value: '' }
]

export const animationList = [
  { value: '' }
]
